#!/usr/bin/env python3
"""Build index.html — the landing page of the published site and of a clone.

GitHub cannot display dashboard.html (the whole databank in one file of some
tens of MB) and serves its «raw» link as sandboxed plain text, so a visitor
needs one address that simply opens it.
With GitHub Pages serving the repository, that address is this page:
https://jastephan63.github.io/citygov/ . It links the dashboard, the guided
flows, the dossiers and the repository, states size and data date, and says
how to keep an offline copy. Figures come from data_export.json (one source),
so the page never drifts from the dashboard; the dashboard's size and transfer
size are measured on dashboard.html with the same rounding the dashboard uses
for itself (common.size_txt / net_size_txt). Also writes 404.html, which GitHub
Pages serves for any missing path.

The look (font, ink, link colour, text sizes) comes from scripts/theme.py; every
value written into the two pages passes e() — text and attribute values alike.
The pages carry no script and inline no data.

    python3 scripts/build_index.py        (run by ./build.sh)
"""
import html, json, os, sys
from citygov.core.common import ROOT, EXPORT_PATH, size_txt, net_size_txt
from citygov.core.labels import fmt_date
from citygov.core import theme as THEME

SITE = "https://jastephan63.github.io/citygov/"
REPO = "https://github.com/jastephan63/citygov"


def dash_size():
    """«knapp 30 MB, über das Netz etwa 4 MB» for dashboard.html as it is on disk."""
    try:
        raw = open(os.path.join(ROOT, "dashboard.html"), "rb").read()
    except OSError:
        sys.exit("dashboard.html fehlt — zuerst scripts/build_dashboard.py ausführen")
    return f"knapp {size_txt(len(raw))}, über das Netz etwa {net_size_txt(raw)}"


def main():
    D = json.load(open(EXPORT_PATH, encoding="utf-8"))
    ds = D.get("datenstand") or {}
    n_services, n_forms = len(D["services"]), len(D["forms"])
    n_fields = sum(len(f.get("data_fields") or []) for f in D["forms"])
    n_flows = sum(1 for f in D["forms"] if f.get("has_flow"))
    n_dossiers = len([x for x in os.listdir(os.path.join(ROOT, "dossiers")) if x.endswith(".html") and x != "index.html"]) \
        if os.path.isdir(os.path.join(ROOT, "dossiers")) else 0
    dash = dash_size()
    fields_txt = f"{n_fields:,}".replace(",", "'")      # thousands grouped as on the dashboard: 5'991

    def e(v):
        """A value on its way into the page, as text or inside a quoted attribute."""
        return html.escape(str(v if v is not None else ""), quote=True)
    stand = " · ".join(x for x in (
        f"Daten exportiert {fmt_date(ds.get('build'))}" if ds.get("build") else "",
        f"DVSH-Modell {fmt_date(ds.get('dvsh_stand'))}" if ds.get("dvsh_stand") else "",
        f"SHEP-Portal {fmt_date(ds.get('shep_harvest'))}" if ds.get("shep_harvest") else "") if x)

    page = f"""<!-- GENERATED by scripts/build_index.py from data_export.json — do not edit; run ./build.sh -->
<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="utf-8">{THEME.favicon()}
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Compliance-Databank Kanton Schaffhausen</title>
<meta name="description" content="Maschinenlesbare Compliance-Databank der Verwaltung des Kantons Schaffhausen: Formulare, Datenfelder, Rechtsgrundlagen, Standards, Datenhandhabung.">
<style>
{THEME.css_root()}
  /* landing page: the look of the dashboard (scripts/theme.py), larger running text */
  *{{box-sizing:border-box}}
  body{{margin:0;background:var(--paper);color:var(--ink);font:var(--fs-l)/1.55 var(--font)}}
  main{{max-width:880px;margin:0 auto;padding:40px 20px 64px}}
  .kicker{{font-size:var(--fs-xs);letter-spacing:.08em;text-transform:uppercase;color:var(--ink-soft);display:flex;align-items:center;gap:10px}}
  .kicker i{{display:inline-block;width:22px;height:22px;border-radius:5px;background:var(--gold)}}
  h1{{font-size:var(--fs-xxl);line-height:1.2;margin:10px 0 12px}}
  .lead{{color:var(--ink-soft);margin:0 0 28px;max-width:720px}}
  .open{{display:block;background:var(--ink);color:var(--card);text-decoration:none;border-radius:12px;padding:22px 24px;margin:0 0 14px}}
  .open b{{font-size:var(--fs-xl);display:block}}
  .open span{{color:var(--line);font-size:var(--fs-m)}}
  .open:hover{{background:var(--ink-soft)}}
  .grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;margin:0 0 30px}}
  .card{{display:block;background:var(--card);border:1px solid var(--line);border-radius:12px;padding:18px 20px;text-decoration:none;color:inherit}}
  .card:hover{{border-color:var(--gold-deep);background:var(--hover)}}
  .card b{{display:block;font-size:var(--fs-l);margin-bottom:4px}}
  .card span{{font-size:var(--fs-m);color:var(--ink-soft)}}
  .facts{{display:flex;flex-wrap:wrap;gap:8px 22px;font-size:var(--fs-m);color:var(--ink-soft);margin:0 0 30px}}
  .facts b{{color:var(--ink);font-size:var(--fs-l);margin-right:4px}}
  .facts.stand{{margin-top:-18px}}
  h2{{font-size:var(--fs-xl);margin:34px 0 8px}}
  p,li{{font-size:var(--fs-l)}}
  ol{{padding-left:22px}}
  .note{{font-size:var(--fs-s);color:var(--ink-soft);border-top:1px solid var(--line);margin-top:36px;padding-top:14px}}
  code{{font-family:var(--mono);font-size:var(--fs-s);background:var(--field);padding:1px 5px;border-radius:4px}}
  a{{color:var(--link);text-underline-offset:2px}}
</style>
</head>
<body>
<main>
  <div class="kicker"><i></i>Kanton Schaffhausen</div>
  <h1>Compliance-Databank · Datenstandards, Formulare &amp; Recht</h1>
  <p class="lead">Für jeden Service der kantonalen Verwaltung: welche Daten seine Formulare erheben (bis zum
  einzelnen Teilfeld) und nach welchem Standard (eCH bzw. der kantonale Entwurf eSH), ob dieselbe Angabe überall
  gleich verlangt und gleich benannt wird, die Gesetze dahinter (artikelgenau) und die Regeln für Speichern,
  Weitergeben und Löschen — und was noch fehlt. Lücken stehen als Lücken da.</p>

  <a class="open" href="dashboard.html"><b>▶ Dashboard öffnen</b>
    <span>Eine Seite mit allen Daten ({e(dash)}) — beim ersten Öffnen dauert das Laden je nach Verbindung und Gerät einige Sekunden.</span></a>

  <div class="grid">
    <a class="card" href="dashboard.html#dienststellen"><b>Für Dienststellen</b>
      <span>Was muss ich an meinen Formularen ändern? Eine Seite je Dienststelle mit den wichtigsten Massnahmen, druckbar.</span></a>
    <a class="card" href="dashboard.html#kanton"><b>Für den Kanton</b>
      <span>Was muss entschieden werden — zuerst beim Datenstandard?</span></a>
    <a class="card" href="dashboard.html#methode"><b>Für Fachleute</b>
      <span>Wie ist die Databank gebaut: Methode, Quellen, Prüfungen, Verlauf.</span></a>
  </div>
  <div class="grid">
    <a class="card" href="dossiers/index.html"><b>Datenschutz-Dossiers</b>
      <span>{e(n_dossiers)} druckbare Seiten, eine je Service — Rechtsgrundlagen, Daten, Handhabung, offene Punkte.</span></a>
    <a class="card" href="flows.html"><b>Geführte Formulare (Prototyp)</b>
      <span>Schritt-für-Schritt-Abläufe für {e(n_flows)} von {e(n_forms)} Formularen. Antworten bleiben nur in diesem
      Browser gespeichert.</span></a>
    <a class="card" href="{e(REPO)}"><b>Quellcode &amp; Dokumentation</b>
      <span>Das Repository auf GitHub: Datenbank, Skripte, maschinenlesbare Exporte, README (englisch).</span></a>
  </div>

  <div class="facts"><span><b>{e(n_services)}</b>Services</span><span><b>{e(n_forms)}</b>Formulare</span>
    <span><b>{e(fields_txt)}</b>Datenfelder</span></div>
  <p class="facts stand">{e(stand)}</p>

  <h2>Offline verwenden</h2>
  <ol>
    <li>Mit der rechten Maustaste (Mac: Ctrl-Klick) auf <b>«Dashboard öffnen»</b> klicken und
      <b>«Link speichern unter …»</b> wählen (Firefox: «Ziel speichern unter …», Safari: «Verknüpfte Datei laden»).</li>
    <li>Die gespeicherte Datei <code>dashboard.html</code> per Doppelklick öffnen — sie läuft ohne Internet in
      jedem aktuellen Browser (Chrome, Edge, Firefox, Safari).</li>
  </ol>
  <p>In einer solchen Einzelkopie öffnen sich Dossiers, Quelldateien und geführte Formulare auf dieser Website.
  Ganz ohne Internet gehen sie nur mit dem ganzen Repository (auf GitHub «Code» → «Download ZIP», rund 170 MB;
  danach <code>index.html</code> öffnen).</p>

  <p class="note">German-language compliance databank of the Canton of Schaffhausen, built for peers working on
  similar databanks. Documentation in English: <a href="{e(REPO)}#readme">README on GitHub</a>.
  Alle Personendaten in den Beispielen sind frei erfunden (synthetisch).</p>
</main>
</body>
</html>
"""
    out = os.path.join(ROOT, "index.html")
    open(out, "w", encoding="utf-8").write(page)
    # GitHub Pages serves 404.html for any missing path, at the depth of the wrong
    # URL — so every link here is absolute
    open(os.path.join(ROOT, "404.html"), "w", encoding="utf-8").write(f"""<!-- GENERATED by scripts/build_index.py — do not edit; run ./build.sh -->
<!DOCTYPE html>
<html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
{THEME.favicon()}
<title>Seite nicht gefunden · Compliance-Databank Kanton Schaffhausen</title>
<style>
{THEME.css_root(compact=True)}
body{{margin:0;background:var(--paper);color:var(--ink);font:var(--fs-l)/1.55 var(--font)}}
main{{max-width:680px;margin:0 auto;padding:56px 20px}} h1{{font-size:var(--fs-xxl);margin:0 0 10px}} p{{color:var(--ink-soft)}}
a.b{{display:inline-block;margin:10px 10px 0 0;padding:12px 18px;border-radius:10px;background:var(--ink);color:var(--card);text-decoration:none}}
a.b:hover{{background:var(--ink-soft)}}
a.s{{display:inline-block;margin:10px 10px 0 0;color:var(--link)}}</style></head>
<body><main><h1>Seite nicht gefunden</h1>
<p>Diese Adresse gibt es auf der Website der Compliance-Databank nicht (mehr) — vielleicht ein veralteter oder
vertippter Link. Gross- und Kleinschreibung zählen.</p>
<a class="b" href="{e(SITE)}">Zur Startseite</a><a class="b" href="{e(SITE)}dashboard.html">Dashboard öffnen</a><br>
<a class="s" href="{e(SITE)}dossiers/index.html">Datenschutz-Dossiers</a> · <a class="s" href="{e(REPO)}">Repository auf GitHub</a>
</main></body></html>
""")
    print(f"wrote {out}  ({n_services} Services, {n_forms} Formulare, {n_dossiers} Dossiers, {n_flows} Flows)")


if __name__ == "__main__":
    main()
