#!/usr/bin/env python3
"""Build index.html — the landing page of the published site and of a clone.

GitHub cannot display dashboard.html (38 MB) and serves its «raw» link as
sandboxed plain text, so a visitor needs one address that simply opens it.
With GitHub Pages serving the repository, that address is this page:
https://jastephan63.github.io/citygov/ . It links the dashboard, the guided
flows, the dossiers and the repository, states size and data date, and says
how to keep an offline copy. Figures come from data_export.json (one source),
so the page never drifts from the dashboard.

    python3 scripts/build_index.py        (run by ./build.sh)
"""
import html, json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ROOT, EXPORT_PATH
from labels import fmt_date

SITE = "https://jastephan63.github.io/citygov/"
REPO = "https://github.com/jastephan63/citygov"


def size_txt(m):
    """«40 MB» style, rounded UP to the next 10 MB: true in decimal and binary units."""
    import math
    return f"{int(math.ceil((m or 0) / 10.0) * 10)} MB" if m else "40 MB"


def mb(path):
    try:
        return os.path.getsize(os.path.join(ROOT, path)) / 1e6
    except OSError:
        return None


def main():
    D = json.load(open(EXPORT_PATH, encoding="utf-8"))
    ds = D.get("datenstand") or {}
    n_services, n_forms = len(D["services"]), len(D["forms"])
    n_fields = sum(len(f.get("data_fields") or []) for f in D["forms"])
    n_flows = sum(1 for f in D["forms"] if f.get("has_flow"))
    n_dossiers = len([x for x in os.listdir(os.path.join(ROOT, "dossiers")) if x.endswith(".html") and x != "index.html"]) \
        if os.path.isdir(os.path.join(ROOT, "dossiers")) else 0
    dash_mb, flows_mb = mb("dashboard.html"), mb("flows.html")
    e = html.escape
    stand = " · ".join(x for x in (
        f"Daten exportiert {fmt_date(ds.get('build'))}" if ds.get("build") else "",
        f"DVSH-Modell {fmt_date(ds.get('dvsh_stand'))}" if ds.get("dvsh_stand") else "",
        f"SHEP-Portal {fmt_date(ds.get('shep_harvest'))}" if ds.get("shep_harvest") else "") if x)

    page = f"""<!-- GENERATED by scripts/build_index.py from data_export.json — do not edit; run ./build.sh -->
<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="utf-8"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%23e8b100'/%3E%3C/svg%3E">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Compliance-Databank Kanton Schaffhausen</title>
<meta name="description" content="Maschinenlesbare Compliance-Databank der Verwaltung des Kantons Schaffhausen: Formulare, Datenfelder, Rechtsgrundlagen, Standards, Datenhandhabung.">
<style>
  :root{{--paper:#FAFAF6;--card:#FFFFFF;--ink:#1d1d1b;--ink-soft:#5b5b55;--line:#e3dfd2;--accent:#c8102e;--gold:#e8b100}}
  *{{box-sizing:border-box}}
  body{{margin:0;background:var(--paper);color:var(--ink);font:16px/1.55 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}}
  main{{max-width:880px;margin:0 auto;padding:40px 20px 64px}}
  .kicker{{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:var(--ink-soft);display:flex;align-items:center;gap:10px}}
  .kicker i{{display:inline-block;width:22px;height:22px;border-radius:5px;background:var(--gold)}}
  h1{{font-size:30px;line-height:1.2;margin:10px 0 12px}}
  .lead{{color:var(--ink-soft);margin:0 0 28px;max-width:720px}}
  .open{{display:block;background:var(--ink);color:#fff;text-decoration:none;border-radius:12px;padding:22px 24px;margin:0 0 14px}}
  .open b{{font-size:21px;display:block}}
  .open span{{color:#d9d6cc;font-size:14px}}
  .open:hover{{background:#000}}
  .grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;margin:0 0 30px}}
  .card{{display:block;background:var(--card);border:1px solid var(--line);border-radius:12px;padding:18px 20px;text-decoration:none;color:inherit}}
  .card:hover{{border-color:var(--ink-soft)}}
  .card b{{display:block;font-size:17px;margin-bottom:4px}}
  .card span{{font-size:14px;color:var(--ink-soft)}}
  .facts{{display:flex;flex-wrap:wrap;gap:8px 22px;font-size:14px;color:var(--ink-soft);margin:0 0 30px}}
  .facts b{{color:var(--ink);font-size:18px;margin-right:4px}}
  h2{{font-size:18px;margin:34px 0 8px}}
  p,li{{font-size:15px}}
  ol{{padding-left:22px}}
  .note{{font-size:13px;color:var(--ink-soft);border-top:1px solid var(--line);margin-top:36px;padding-top:14px}}
  code{{font-family:"Roboto Mono",ui-monospace,Menlo,Consolas,monospace;font-size:13px;background:#f1eee4;padding:1px 5px;border-radius:4px}}
  a{{color:var(--ink)}}
</style>
</head>
<body>
<main>
  <div class="kicker"><i></i>Kanton Schaffhausen</div>
  <h1>Compliance-Databank · Formulare, Recht &amp; Standards</h1>
  <p class="lead">Für jeden Service der kantonalen Verwaltung: die Gesetze dahinter (artikelgenau), die Daten,
  die seine Formulare erheben (bis zum einzelnen Teilfeld), den Standard jedes Datums (eCH bzw. der kantonale
  Entwurf eSH), die Regeln für Speichern, Weitergeben und Löschen — und was noch fehlt. Lücken stehen als Lücken da.</p>

  <a class="open" href="dashboard.html"><b>▶ Dashboard öffnen</b>
    <span>Eine Seite mit allen Daten (knapp {size_txt(dash_mb)}, über das Netz etwa 5 MB) — beim ersten Öffnen dauert das Laden je nach Verbindung und Gerät einige Sekunden.</span></a>

  <div class="grid">
    <a class="card" href="dossiers/index.html"><b>Datenschutz-Dossiers</b>
      <span>{n_dossiers} druckbare Seiten, eine je Service — Rechtsgrundlagen, Daten, Handhabung, offene Punkte.</span></a>
    <a class="card" href="flows.html"><b>Geführte Formulare (Prototyp)</b>
      <span>Schritt-für-Schritt-Abläufe für {n_flows} von {n_forms} Formularen.</span></a>
    <a class="card" href="{REPO}"><b>Quellcode &amp; Dokumentation</b>
      <span>Das Repository auf GitHub: Datenbank, Skripte, maschinenlesbare Exporte, README (englisch).</span></a>
  </div>

  <div class="facts"><span><b>{n_services}</b>Services</span><span><b>{n_forms}</b>Formulare</span>
    <span><b>{str(f'{n_fields:,}').replace(',', chr(39))}</b>Datenfelder</span></div>
  <p class="facts" style="margin-top:-18px">{e(stand)}</p>

  <h2>Offline verwenden</h2>
  <ol>
    <li>Mit der rechten Maustaste auf <b>«Dashboard öffnen»</b> klicken und <b>«Link speichern unter …»</b>
      (bzw. «Ziel speichern unter …») wählen.</li>
    <li>Die gespeicherte Datei <code>dashboard.html</code> per Doppelklick öffnen — sie läuft ohne Internet in
      jedem aktuellen Browser (Chrome, Edge, Firefox, Safari).</li>
  </ol>
  <p>Die Verweise auf Dossiers und Quelldateien der Formulare funktionieren offline nur mit dem ganzen
  Repository (auf GitHub «Code» → «Download ZIP», rund 170 MB).</p>

  <p class="note">German-language compliance databank of the Canton of Schaffhausen, built for peers working on
  similar databanks. Documentation in English: <a href="{REPO}#readme">README on GitHub</a>.
  Die Daten im Beispiel-Datentresor sind vollständig synthetisch. Generiert aus <code>citygov.db</code>; nicht von Hand bearbeiten.</p>
</main>
</body>
</html>
"""
    out = os.path.join(ROOT, "index.html")
    open(out, "w", encoding="utf-8").write(page)
    print(f"wrote {out}  ({n_services} Services, {n_forms} Formulare, {n_dossiers} Dossiers, {n_flows} Flows)")


if __name__ == "__main__":
    main()
