#!/usr/bin/env python3
"""One Datenschutz-Dossier per service, as a small self-contained HTML page
(dossiers/<slug>.html) and - with --pdf and a local Chrome - as PDF.

Why: a Dienststelle should get its own picture on one to four A4 pages (longer
where a Formular has many Standard-Divergenzen) without opening the dashboard
(about 37 MB). Everything on the page comes from data_export.json, i.e. from
citygov.db, and says what it is: verified, curated, derived or open. Nothing
here is a new judgment: the labels come from scripts/labels.py, the
Handlungsbedarf from export_json.py (form.handlungsbedarf), the default
retention sentence from data.texte - the same places the dashboard reads.

Contents: Service (Dienststelle, Kontakt aus dem DVSH, DVSH-Status, Zweck),
Rechtsgrundlagen des Services, Verfahrens-Ergebnis und Rechtsmittel, je
Formular: Kanal/Unterschrift/Bürgerlast, die Datenfelder (Pflicht, eCH-Element
und Datentyp, Grundlage, ⛨, ↺), Beilagen mit Halter, Empfänger mit Artikel,
Aufbewahrung, Standard-Divergenzen und der Handlungsbedarf des Formulars; a
printed legend explains the glyphs, the footer states the Datenstand.

    python3 scripts/export_dossiers.py [--pdf] [--only <service_id>]
"""
import html, json, os, re, subprocess, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import labels as LABELS
from labels import fmt_date, pl, render_label

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dossiers")
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
GENERATED = ("<!-- GENERATED by scripts/export_dossiers.py from citygov.db via data_export.json "
             "— do not edit; run python3 scripts/export_dossiers.py -->")

# filled in main() from data_export.json: the DATA date (ISO, printed through
# labels.fmt_date like every date on the dashboard) and the data's own
# provenance, never the render date
STAND = ""
TEXTE = {}
DATENSTAND = {}
ZITATE = {}

esc = lambda s: html.escape(str(s if s is not None else ""), quote=True)

# the dashboard's badge classes (named in labels.TODO_CATS) -> the dossier's
BCLS = {"b-unver": "warn", "b-over": "bad", "b-sens": "sens", "b-sourced": "ok", "b-match": "ok"}
# gesetzesebenen -> wording of the Rechtsmittel line; mirrors the inline literal in
# build_dashboard.py (rechtsmittelLine) and belongs in labels.py with the other maps —
# labels.JUR says «Bund/Kanton/Gemeinde», which is not the same sentence, so it is
# kept here until labels.py carries it for both surfaces
EBENE = LABELS.EBENE          # level of law, sentence form — shared with the dashboard

CSS = """
@page{size:A4;margin:14mm 14mm 16mm}
*{box-sizing:border-box}
:root{color-scheme:light only}
body{font:10.5pt/1.35 -apple-system,"Helvetica Neue",Arial,sans-serif;color:#1F2A37;background:#fff;margin:0;padding:18px 22px;max-width:900px}
h1{font-size:16pt;margin:0 0 2px}h2{font-size:11.5pt;margin:14px 0 4px;border-bottom:1px solid #D8D2C4;padding-bottom:2px}
h3{font-size:10.5pt;margin:10px 0 3px}
.sub{color:#6B6455;font-size:9.5pt}.muted{color:#6B6455}.small{font-size:9pt}
a{color:#8F6400}a:hover{text-decoration:none}a.b{text-decoration:none}
table{border-collapse:collapse;width:100%;font-size:9pt}th,td{text-align:left;vertical-align:top;padding:2px 5px;border-bottom:1px solid #EAE5DA}
th{font-weight:600;color:#6B6455;font-size:8.5pt;text-transform:uppercase;letter-spacing:.03em}
.b{display:inline-block;border:1px solid #D8D2C4;border-radius:4px;padding:0 4px;font-size:8.5pt;white-space:nowrap}
.b.ok{color:#1F5A3A;background:#E3F2E8;border-color:#B9DEC6}.b.warn{color:#8F6400;background:#FBF3DC;border-color:#EBD9A8}
.b.bad{color:#7A1F1F;background:#FBEAEA;border-color:#E8B4B4}.b.sens{color:#5A1F6B;background:#F1E6F5;border-color:#D7BFE0}
.b.info{color:#1F3A6B;background:#E6ECF5;border-color:#BFCDE0}
.mono{font-family:ui-monospace,Menlo,monospace;font-size:8.5pt}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:6px 18px}
.box{border:1px solid #D8D2C4;border-radius:6px;padding:6px 9px;margin:6px 0}
.print{position:fixed;right:14px;top:10px;border:1px solid #D8D2C4;background:#fff;border-radius:6px;padding:5px 10px;font:inherit;cursor:pointer}
.nav{font-size:9.5pt;margin:0 0 8px}.nav a{margin-right:12px}
.todo{margin:2px 0}
.legend{margin-top:12px;font-size:8.5pt;color:#6B6455;border-top:1px dashed #D8D2C4;padding-top:4px}
.foot{margin-top:10px;font-size:8.5pt;color:#6B6455;border-top:1px solid #D8D2C4;padding-top:4px}
input.filter{font:inherit;padding:4px 8px;border:1px solid #D8D2C4;border-radius:6px;margin:8px 0;width:360px;max-width:100%}
@media print{.print,.nav,input.filter{display:none}body{padding:0}h2,h3{break-after:avoid}tr{break-inside:avoid}thead{display:table-header-group}
.b{white-space:normal}a{color:inherit;text-decoration:none}a[href^=http]::after{content:' (' attr(href) ')';font-size:7.5pt;color:#6B6455}}
"""


# short title -> jurisdiction, filled from the law table in main(); used to read
# the level of a DVSH legal reference instead of trusting the list it sits in
LAWJUR = {}


def abbrs_of(label):
    """Every candidate short title in a free-text reference: each parenthesised
    abbreviation plus the trailing token ("Art. 3 GesG" -> GesG)."""
    out = [m.group(1) for m in re.finditer(r"\(([^)]{2,24})\)", label or "")]
    parts = (label or "").strip().split()
    if parts:
        out.append(parts[-1])
    return out


def jur_of_ref(x, label, local=None):
    """Bund / Kanton / Ebene offen for one free-text DVSH legal reference.

    The modeller's «recht_bund» list is free text ("Art. 3 GesG", a rechtsbuch
    link, a title) and regularly holds CANTONAL law, so the level is read from
    evidence only: the URL host, an SR/SHR marker, a short title the databank
    knows, or the titled entry in the SAME list that shares the abbreviation.
    Nothing is assumed.
    """
    url = x.get("url") or ""
    if "rechtsbuch.sh.ch" in url or re.search(r"\bSHR\b", label) or re.match(r"(?i)kantonale?s?\b", label):
        return "Kanton"
    if (re.search(r"(^|\.)admin\.ch", url) or re.search(r"\bSR\s?\d", label)
            or re.match(r"(?i)(bundesgesetz|bundesverfassung|bundesbeschluss|bundesratsbeschluss)\b", label)):
        return "Bund"
    if re.match(r"(?i)(interkantonale?s?|konkordat)\b", label):
        return "interkantonal"
    for a in abbrs_of(label):
        j = LABELS.JUR.get(LAWJUR.get(a.lower())) or (local or {}).get(a.lower())
        if j:
            return j
    return "Ebene offen"


def cut(s, n=300):
    """Truncate at the last space before n characters and mark the cut — a legal
    quote never ends mid-word."""
    s = (s or "").strip()
    if len(s) <= n:
        return s
    head = s[:n]
    sp = head.rfind(" ")
    return (head[:sp] if sp > n // 2 else head).rstrip(" ,;·") + " …"


def basis_label(d):
    if d.get("legal_basis"):
        b = d["legal_basis"][0]
        nr = b.get("sr_number") or b.get("cantonal_ref") or ""
        lc = b.get("last_checked") or ""
        # the proof level of the citation: live-checked, or read from the
        # official PDF and still awaiting the live check
        if lc == "verified":
            prov, cls = "verifiziert", "ok"
        elif lc.startswith("Gesetze-PDF"):
            prov, cls = ("Quelle SHR-PDF" if b.get("jurisdiction") == "cantonal" else "Quelle Gesetzes-PDF") + " · Live-Abgleich offen", "ok"
        else:
            prov, cls = "Zitat nicht verifiziert", "warn"
        return (f'<span class="b {cls}">{esc(b.get("article_no"))} {esc((b.get("law_short") or "").strip())}'
                f'{(" · " + esc(nr)) if nr else ""}</span> <span class="small muted">{prov}</span>')
    if d.get("art5_offen"):
        # a besonders schützenswertes Datum judged «aufgabe»: KDSG Art. 4 Abs. 1
        # lit. b is not enough, Art. 5 Abs. 1 lit. a or b must be named -> OPEN
        return ('<span class="b warn">aufgabennotwendig — Grundlage nach KDSG Art. 5 Abs. 1 noch nicht benannt</span>')
    bt = d.get("basis_typ")
    if bt == "aufgabe":
        return f'<span class="b info">{esc(render_label(LABELS.BASIS_TYP, bt))} (KDSG Art. 4 Abs. 1 lit. b) — keine explizite Norm</span>'
    if bt == "ohne":
        return f'<span class="b bad">{esc(render_label(LABELS.BASIS_TYP, bt))} — weder Norm noch Aufgabenbedarf</span>'
    if bt == "offen":
        return f'<span class="b warn">{esc(render_label(LABELS.BASIS_TYP, bt))} — keine explizite Norm</span>'
    if bt:
        return f'<span class="b warn">{esc(render_label(LABELS.BASIS_TYP, bt))}</span>'
    return '<span class="b warn">Rechtsgrundlage zu ermitteln</span>'


def std_badge(e):
    """The standard's own status when it is not in force (Sistiert, In Arbeit …)."""
    return f' <span class="b warn">{esc(e["status"])}</span>' if e.get("status") and e["status"] != "Genehmigt" else ""


def ech_cell(d):
    e = d.get("ech") or {}
    st = std_badge(e)
    if e.get("element"):
        el = (f'<span class="mono">{esc(e["standard"])} {esc(e["element"])}</span>'
              + (f' <span class="mono muted">⟨{esc(e["datatype"])}⟩</span>' if e.get("datatype") else "") + st)
    elif e.get("standard"):
        # an element is only owed where the databank holds an element catalogue
        # for the standard; without one (process/FHIR standard or XSD not swept)
        # the mapping stays on standard level — labels.DIV words it
        note = "Element offen" if e.get("n_elements") else render_label(LABELS.DIV, "standard_ohne_elemente")
        el = f'<span class="mono">{esc(e["standard"])}</span> <span class="muted">{esc(note)}</span>' + st
    elif d.get("ech_status") == "kein_standard":
        el = ('<span class="muted">kein eCH-Standard</span>'
              + (f' <span class="b info">{esc(d["esh"]["code"])} Entwurf (eSH)</span>' if d.get("esh") else ""))
    else:
        el = '<span class="muted">nicht geprüft</span>'
    # sub-fields carry their own elements and their own standard status
    subs = [s for s in (d.get("subfields") or []) if isinstance(s, dict)]
    if subs:
        with_el = [s for s in subs if (s.get("ech") or {}).get("element")]
        stds = []
        for s in with_el:
            if s["ech"]["standard"] not in stds:
                stds.append(s["ech"]["standard"])
        badges, seen = "", set()
        for s in subs:
            se = s.get("ech") or {}
            key = (se.get("standard"), se.get("status"))
            if se.get("status") and se["status"] != "Genehmigt" and key not in seen:
                seen.add(key)
                badges += f' <span class="b warn">{esc(se.get("standard") or "")} {esc(se["status"])}</span>'
        el += (f'<div class="small muted">Teilfelder: {len(with_el)} von {len(subs)} eCH-zugeordnet'
               + (f' ({esc(", ".join(stds[:4]))}{"…" if len(stds) > 4 else ""})' if stds else "")
               + badges + "</div>")
    return el


def field_row(d):
    marks = ""
    if d.get("sensitive"):
        marks += f' <span class="b sens">⛨ {esc(render_label(LABELS.SENS, d["sensitive"]))}</span>'
    units = [s for s in (d.get("subfields") or []) if isinstance(s, dict)] or [d]
    if any(u.get("register") for u in units):
        marks += ' <span class="b ok">↺ Einwohnerregister</span>'
    typ = render_label(LABELS.DFTYPE, d.get("data_type"))
    subs = [s.get("name") if isinstance(s, dict) else s for s in (d.get("subfields") or [])]
    subs_txt = (f'<div class="small muted">Teilfelder: {esc(cut(" · ".join(x for x in subs if x), 160))}</div>'
                if subs else "")
    return (f'<tr><td><b>{esc(d["name"])}</b>{(" <span class=" + chr(34) + "small muted" + chr(34) + ">· " + esc(typ) + "</span>") if typ else ""}'
            f'{marks}{subs_txt}</td>'
            f'<td>{"Pflicht" if d.get("required") else "<span class=muted>optional</span>"}</td>'
            f'<td>{ech_cell(d)}</td><td>{basis_label(d)}</td></tr>')


def todo_html(f):
    """form.handlungsbedarf as computed ONCE in export_json.py, worded by labels.TODO_BY."""
    items = f.get("handlungsbedarf") or []
    if not items:
        return "<span class='b ok'>keine offenen Punkte</span>"
    out = []
    for it in items:
        c = LABELS.TODO_BY.get(it.get("cat"))
        label = c[1] if c else f"⟨{it.get('cat')}⟩"
        cls = BCLS.get(c[2], "warn") if c else "warn"
        art = render_label(LABELS.TODO_ART, c[3]) if c else ""
        n = it.get("n") or 0
        det = cut(it.get("detail") or "", 240)
        tail = " — ".join(x for x in (esc(art), esc(det)) if x)
        out.append(f"<div class='todo'><span class='b {cls}'>{esc(label)}{(': ' + str(n)) if n > 1 else ''}</span>"
                   + (f" <span class='small muted'>{tail}</span>" if tail else "") + "</div>")
    return "".join(out)


def ergebnis_html(out, forms):
    ea = out.get("entscheid_art")
    if not forms:
        # the Verfahren is modelled on a Formular; no Formular, no Verfahren — said
        # without «nicht modelliert», which the head line uses for the DVSH state
        val = ('<span class="small muted">in der Databank nicht erfasst — das Verfahren wird am Formular '
               'modelliert, und für diesen Service liegt keines in der Databank</span>')
    elif not ea:
        val = '<span class="small muted">noch nicht erfasst (Wissenslücke der Databank)</span>'
    elif ea == "unbekannt":
        val = f'<span class="b warn">{esc(render_label(LABELS.OUTCOME, ea))}</span>'
    else:
        val = (esc(render_label(LABELS.OUTCOME, ea))
               + (f' — «{esc(out["ergebnis_dokument"])}»' if out.get("ergebnis_dokument") else "")
               + ' <span class="small muted">(aus dem DVSH-Ablauftext abgeleitet)</span>')
    return f"<div><b>Ergebnis des Verfahrens:</b> {val}</div>"


def rechtsmittel_html(out):
    """The remedy line in its four states: stated (sektoral / VRG confirmed / VRG
    default), assessed and open, not yet assessed, outcome itself not backed."""
    rm = out.get("rechtsmittel")
    stt = out.get("rechtsmittel_status")
    if rm:
        frist = f"innert {rm['frist_tage']} Tagen" if rm.get("frist_tage") else "Frist im Gesetz nicht beziffert"
        nr = ((("SR " if rm.get("jurisdiction_level") == "federal" else "SHR ") + rm["sr_number"]) if rm.get("sr_number")
              else (rm.get("cantonal_ref") or ""))
        what = (f"Rechtsmittel nach {esc(rm.get('instanz') or 'dem verwiesenen Erlass')}" if rm.get("rechtsmittel_art") == "verweis"
                else f"<b>{esc(render_label(LABELS.RM, rm.get('rechtsmittel_art')))}</b>"
                     f"{(' an ' + esc(rm['instanz'])) if rm.get('instanz') else ''} {frist}")
        if rm.get("scope") == "allgemein":
            if stt == "default_allgemein":
                src = (f'<span class="b warn">{esc(render_label(LABELS.RM_STATUS, stt))}</span> '
                       '<span class="small muted">VRG Art. 1: die allgemeine Regel gilt nur, soweit kein Fachgesetz abweicht — '
                       'ob eines vorgeht, hat noch kein Prüfvermerk bestätigt.</span>')
            else:
                src = '<span class="b ok">allgemeine Regel des VRG — Prüfvermerk bestätigt, kein vorgehendes Fachgesetz</span>'
        else:
            src = f'<span class="b ok">sektoral: {esc(rm.get("short_title") or rm.get("law_title") or "")}</span>'
        h = [f'<div><b>Rechtsmittel:</b> {what} — {esc(rm.get("article_no"))} {esc(rm.get("short_title") or rm.get("law_title") or "")}'
             f'{(" (" + esc(nr) + ")") if nr else ""} {src}</div>',
             f'<div class="small muted">«{esc(cut(rm.get("quote"), 300))}»</div>']
        if rm.get("frist_quote"):
            h.append(f'<div class="small muted">«{esc(cut(rm["frist_quote"], 300))}»</div>')
        if rm.get("hinweis"):
            h.append(f'<div class="small muted">{esc(rm["hinweis"])}</div>')
        h.append(verdikt_html(out))
        return "".join(h)
    if out.get("entscheid_art") == "kein_entscheid":
        return '<div><b>Rechtsmittel:</b> <span class="muted">keines — das Verfahren endet ohne anfechtbare Verfügung (Meldung)</span></div>'
    if not stt:
        return ""
    h = [f'<div><b>Rechtsmittel:</b> <span class="b warn">{esc(render_label(LABELS.RM_STATUS, stt))}</span>']
    if stt in ("beurteilt_offen", "nicht_beurteilt"):
        lv = " und ".join(EBENE.get(x) or render_label(LABELS.JUR, x) for x in (out.get("gesetzesebenen") or [])) \
             or "die zitierten Erlasse"
        h.append(f' <span class="small muted">Der Entscheid stützt sich auf {esc(lv)}'
                 f'{"; Registerverfahren haben oft eine eigene Rechtsmittelordnung" if out.get("entscheid_art") == "registereintrag" else ""}.'
                 f'{" Eine Wissenslücke der Databank, kein Befund." if stt == "nicht_beurteilt" else ""}</span>')
    elif stt == "entscheidart_offen":
        h.append(' <span class="small muted">Erst wenn feststeht, was das Verfahren zurückgibt, lässt sich die '
                 'zuständige Rechtsmittelnorm bestimmen.</span>')
    h.append("</div>")
    h.append(verdikt_html(out))
    return "".join(h)


def rm_quelle_label(code):
    """rechtsmittel_quelle ∈ {allgemein, sektoral, offen}: the first two are the scope
    vocabulary (labels.SCOPE); «offen» is what export_json turns into the status
    beurteilt_offen (labels.RM_STATUS) — no third label source, unknown codes ⟨…⟩."""
    if code == "offen":
        return render_label(LABELS.RM_STATUS, "beurteilt_offen")
    return render_label(LABELS.SCOPE, code)


def verdikt_html(out):
    """The panel's note, stored as «quelle: begruendung»."""
    v = out.get("rechtsmittel_verdikt")
    if not v:
        return ""
    m = re.match(r"^(\w+):\s*(.+)$", v, re.S)
    return (f'<div class="small muted">Prüfvermerk ({esc(rm_quelle_label(m.group(1)))}): {esc(m.group(2))}</div>' if m
            else f'<div class="small muted">Prüfvermerk: {esc(v)}</div>')


def formless_html(s, dv):
    """What a service without a Formular in the databank really is, per the DVSH."""
    if s.get("dvsh") is None:
        # in_dvsh=1 without a row: the service IS in the DVSH, only its
        # modelling is missing from the current harvest — not «nicht modelliert»
        head = ("DVSH-Modellierung nicht in der Databank" if s.get("in_dvsh") else "Nicht im DVSH modelliert")
        return (f"<div class='box small'>{head}; kein Formular in der Databank — "
                "weder eine Feld-Schicht noch ein Verfahren ist erfasst.</div>")
    ep = dv.get("endpoint_typ")
    txt = f"Kein Formular in der Databank — laut DVSH Kanal: {esc(render_label(LABELS.ENDPOINT, ep) or 'im DVSH nicht angegeben')}"
    if ep == "eformular":
        fd = dv.get("form_definitions")
        if isinstance(fd, str):
            try: fd = json.loads(fd)
            except Exception: fd = []
        nfel = sum(len(x.get("felder") or []) for x in (fd or []) if isinstance(x, dict))
        txt += (f" — im DVSH sind {pl(nfel, 'Feld', 'Felder')} hinterlegt, die Feld-Schicht ist in der Databank noch nicht erhoben"
                if nfel else " — im DVSH sind keine Felder hinterlegt, in der Databank gibt es keine Feld-Schicht")
    return f"<div class='box small'>{txt}.</div>"


def legend_html():
    return ("<div class='legend'><b>Legende:</b> ⛨ = besonders schützenswertes Personendatum · "
            "↺ = das Einwohnerregister führt dieses Datum bereits (Once-Only, nur Daten natürlicher Personen; gezählt je Teilfeld) · "
            "⟨Typ⟩ = Datentyp gemäss eCH-XSD · Element offen = Standard zugeordnet, XML-Element noch nicht bestimmt · "
            "Standard ohne Elementkatalog = in der Databank ist für diesen Standard kein XML-Elementkatalog hinterlegt "
            "(Prozess-/FHIR-Standard oder XSD nicht eingelesen); die Zuordnung bleibt auf Standard-Ebene · "
            "Pflicht im Korpus ungeklärt = die Formulare sind gespalten, eine kantonale Festlegung fehlt · "
            "Min. = Rechenmodell 0.4 Min. je Pflichtangabe + 5 Min. je Beilage, keine Messung; Beilage = jeder Eintrag der "
            f"Beilagenliste (Formular und DVSH) plus Felder vom Datentyp {esc(render_label(LABELS.DFTYPE, 'attachment'))} ohne "
            "Listeneintrag, ohne Gewichtung nach Pflicht · "
            "Farben: grün = belegt, blau = aufgabennotwendig (KDSG Art. 4 Abs. 1 lit. b), gelb = offen oder zu klären, "
            "rot = Over-collection oder veraltete Fassung, violett = besonders schützenswert · "
            "Handlungsbedarf: Recherche (Databank) / Entscheid (Kanton) / Bereinigung (Dienststelle) sagt, wer am Zug ist.</div>")


def foot_html():
    ds, oc, xs = DATENSTAND, (DATENSTAND.get("online_check") or {}), (DATENSTAND.get("xsd_sweep") or {})
    bits = [f"Export {fmt_date(STAND)}"]
    if ds.get("dvsh_stand"):
        bits.append(f"DVSH-Stand {fmt_date(ds['dvsh_stand'])}")
    if ds.get("shep_harvest"):
        bits.append(f"SHEP-Abzug {fmt_date(ds['shep_harvest'])}")
    if oc.get("date"):
        # the last FULL pass and the recheck since — the same two dates the
        # dashboard's Datenstand line names (a recheck of 98 Formulare is not
        # «zuletzt geprüft» for all 474)
        full = oc.get("full_date") or oc["date"]
        recheck = (f", Nachprüfung {fmt_date(oc['date'])} ({pl(oc.get('n_recent') or 0, 'Formular', 'Formulare')})"
                   if oc.get("full_date") and oc["date"] != oc["full_date"] else "")
        bits.append(f"Online-Prüfung vollständig {fmt_date(full)}{recheck} — {oc.get('n_checked', 0)} von {oc.get('n_forms', 0)} "
                    f"Formularen geprüft, {pl(oc.get('n_overdue', 0), 'Wiedervorlage überfällig', 'Wiedervorlagen überfällig')}, "
                    f"{oc.get('n_never', 0)} nie geprüft")
    if xs.get("date"):
        bits.append(f"eCH-XSD-Abgleich {fmt_date(xs['date'])} ({pl(xs.get('n') or 0, 'Standard', 'Standards')})")
    z = ZITATE or {}
    # thousands grouped as the dashboard's nf() (de-CH: 2'900)
    nf = lambda n: f"{int(n or 0):,}".replace(",", "'")
    zit = (f" Zitate der Rechtsgrundlagen: {nf(z.get('verifiziert'))} live verifiziert · {nf(z.get('quelle_pdf'))} aus dem "
           f"Gesetzes-PDF (Live-Abgleich offen) · {nf(z.get('unverifiziert'))} unverifiziert." if z else "")
    return ("<div class='foot'>Quelle: citygov.db (Feld-Schicht kuratiert; Rechtsgrundlagen gegen die amtlichen Gesetzestexte geprüft; "
            "eCH aus den offiziellen XSDs; Empfänger und Fristen nur mit Artikel-Beleg). «zu ermitteln» und «offen» sind Wissenslücken "
            "der Databank, keine festgestellten Verstösse. Schutzstufen (ISV) sind für die Felder noch nicht festgelegt — kantonaler "
            f"Entscheid ausstehend.<br>Datenstand: {esc(' · '.join(bits))}.{esc(zit)}</div>")


def dossier(s, forms, dst):
    dv = s.get("dvsh") or {}
    kontakt = []
    if dst and dst.get("kontakt"):
        try:
            kontakt = json.loads(dst["kontakt"])
        except Exception:
            kontakt = [dst["kontakt"]]
    # the DVSH contact starts with the office name, which the line already says
    if kontakt and str(kontakt[0]).strip().lower() == (s.get("dienststelle") or "").strip().lower():
        kontakt = kontakt[1:]
    laws = []
    for key in ("recht_kantonal", "recht_bund"):
        v = dv.get(key)
        if isinstance(v, str):
            try: v = json.loads(v)
            except Exception: v = []
        items = [x for x in (v or []) if isinstance(x, dict)]
        # abbreviation -> level, from the entries of THIS list whose level is
        # established; a bare "Art. 3 GesG" then inherits it
        local = {}
        if key == "recht_bund":
            for x in items:
                lb = (x.get("titel") or x.get("label") or "").strip()
                j = jur_of_ref(x, lb)
                if j == "Ebene offen":
                    continue
                for a in abbrs_of(lb):
                    local[a.lower()] = j
        for x in items:
            label = (x.get("titel") or x.get("label") or "").strip()
            if not label:
                continue
            # the DVSH's second list is free text and often cantonal law; the
            # level is read from evidence, never from the list's name
            jl = "Kanton" if key == "recht_kantonal" else jur_of_ref(x, label, local)
            nr = x.get("ssr_nummer") or x.get("sr_nummer") or ""
            chip = f'{jl} · {esc(label)}{(" · " + esc(nr)) if nr else ""}'
            url = x.get("url") or ""
            if re.match(r"https?://", url):
                laws.append(f'<a class="b" href="{esc(url)}" target="_blank" rel="noreferrer">{chip}</a>')
            else:
                laws.append(f'<span class="b">{chip}</span>')
    # the Entscheid is modelled on ONE of a service's Formulare; picking the
    # first blindly hid the proven Rechtsmittel of the others
    out = next((f["outcome"] for f in forms
                if f.get("outcome") and (f["outcome"].get("rechtsmittel") or f["outcome"].get("entscheid_art"))),
               (forms[0].get("outcome") if forms else None)) or {}
    rm_html = rechtsmittel_html(out)
    if s.get("dvsh") is None:
        # the dashboard's two states (build_dashboard.py, nodvbox): linked in the
        # DVSH but the row is absent from the harvest, vs. not modelled at all
        dv_txt = ("DVSH-Modellierung nicht in der Databank (im DVSH verknüpft, beim letzten Abzug nicht mitgeliefert)"
                  if s.get("in_dvsh") else "nicht modelliert")
    else:
        dv_txt = render_label(LABELS.DVSH_STATUS, dv.get("status")) or "Statuswert im DVSH nicht angegeben"
    if s.get("dvsh_n"):
        dv_txt += f" · eine von {s['dvsh_n']} DVSH-Modellierungen"
    h = [GENERATED,
         f"<!DOCTYPE html><html lang='de'><head><meta charset='utf-8'><link rel='icon' href='data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 32 32%27%3E%3Crect width=%2732%27 height=%2732%27 rx=%277%27 fill=%27%23e8b100%27/%3E%3C/svg%3E'><title>Datenschutz-Dossier · {esc(s['name'])}</title><style>{CSS}</style></head><body>",
         "<button class='print' onclick='window.print()'>⎙ Drucken / als PDF sichern</button>",
         f"<div class='nav'><a href='index.html'>← Alle Dossiers</a> <a href='../dashboard.html#fields/{s['id']}'>Service im Dashboard</a></div>",
         f"<div class='sub'>Kanton Schaffhausen · Compliance-Databank · Datenschutz-Dossier · Stand {fmt_date(STAND)}</div>",
         f"<h1>{esc(s['name'])}</h1>",
         f"<div class='sub'>{esc(s.get('dienststelle') or '')} · {esc(s.get('department') or '')}"
         f"{(' · Kontakt: ' + esc(' · '.join(map(str, kontakt)))) if kontakt else ''}</div>",
         "<div class='grid'>",
         f"<div><b>DVSH-Status (Modeller):</b> {esc(dv_txt)}{' · online' if dv.get('online') else ''}"
         f"{(' · Vollzug: ' + esc(dv.get('vollzugsbehoerde'))) if dv.get('vollzugsbehoerde') else ''}</div>",
         ergebnis_html(out, forms),
         "</div>"]
    if dv.get("kurzbeschreibung"):
        h.append(f"<div class='small'>{esc(cut(dv['kurzbeschreibung'], 400))}</div>")
    if s.get("themen"):
        h.append("<div class='small' style='margin-top:4px'><b>Themengruppe (eCH-0049):</b> " + " · ".join(
            f"{esc(t['gruppe'])} <span class='muted'>({esc(render_label(LABELS.KAT, t.get('katalog')))}, {esc(t['bereich'])})</span>"
            for t in s["themen"]) + "</div>")
    if laws:
        h.append("<h2>Rechtsgrundlagen des Services (DVSH)</h2><div>" + " ".join(laws) + "</div>")
    if rm_html:
        h.append("<h2>Rechtsmittel gegen den Entscheid</h2>" + rm_html)
    for f in forms:
        dfs = f.get("data_fields") or []
        bu = f.get("burden") or {}
        h.append(f"<div class='form'><h2>Formular: {esc(f['title'])}</h2>")
        facts = [esc(render_label(LABELS.CHAN, f.get("submission_channel")) or LABELS.CHAN["unbekannt"])]
        if f.get("signature_requirement"):
            facts.append("Unterschrift: " + esc(render_label(LABELS.SIG, f["signature_requirement"])))
        if bu:
            # the model figure as the dashboard prints it (JS number: 7.0 -> «7», 61.2 -> «61.2»)
            mins = bu.get("minutes") or 0
            mins = int(mins) if float(mins).is_integer() else mins
            facts.append(f"Bürgerlast: {pl(bu.get('inputs', 0), 'Pflichtangabe', 'Pflichtangaben')} (Teilfelder) · "
                         f"{pl(bu.get('attachments', 0), 'Beilage', 'Beilagen')} · ~{mins} Min. (Modell) · "
                         f"{bu.get('prefillable', 0)} aus dem Einwohnerregister vorbefüllbar")
        if f.get("purpose"):
            facts.append("Zweck: " + esc(f["purpose"]))
        ck = f.get("check") or {}
        if ck.get("status") and ck["status"] != "aktuell":
            facts.append(f'<span class="b bad">{esc(render_label(LABELS.CHECK, ck["status"]))}</span>')
        elif ck.get("d"):
            facts.append(f'<span class="muted">Online-Fassung geprüft {esc(fmt_date(ck["d"]))}</span>')
        h.append("<div class='small'>" + " · ".join(facts) + "</div>")
        if dfs:
            h.append("<h3>Verlangte Daten</h3><table><thead><tr><th>Datenfeld</th><th>Pflicht</th><th>Standard / Datentyp</th><th>Rechtsgrundlage</th></tr></thead><tbody>")
            h.extend(field_row(d) for d in dfs)
            h.append("</tbody></table>")
        if f.get("beilagen"):
            parts = []
            for b in f["beilagen"]:
                hl = render_label(LABELS.HALTER, b.get("halter"))
                if b.get("fetchable"):
                    parts.append(f"{esc(b['bezeichnung'])} <span class='b ok'>Once-Only möglich · Halter: {esc(hl)}</span>")
                else:
                    parts.append(f"{esc(b['bezeichnung'])}" + (f" <span class='muted'>(Halter: {esc(hl)})</span>" if hl else ""))
            h.append("<h3>Beilagen</h3><div class='small'>" + " · ".join(parts) + "</div>")
        if f.get("disclosures"):
            h.append("<h3>Empfänger (belegte Bekanntgaben)</h3><div class='small'>" + " · ".join(
                f"{esc(x['empfaenger'])} <span class='muted'>({esc(render_label(LABELS.MODE, x.get('mode')))}"
                f"{(', ' + esc(x.get('short_title') or '') + ' ' + esc(x.get('article_no') or '')) if x.get('article_no') else ''})</span>"
                for x in f["disclosures"]) + "</div>")
        else:
            h.append("<h3>Empfänger</h3><div class='small muted'>keine belegte Bekanntgabe erfasst — offen</div>")
        ret = f.get("retention") or []
        if ret:
            h.append("<h3>Aufbewahrung / Löschung</h3><div class='small'>" + " ".join(
                f"<div>• {esc(r.get('summary') or '')} <span class='muted'>({esc(r.get('short_title') or '')} {esc(r.get('article_no') or '')})</span></div>"
                for r in ret[:4]) + "</div>")
        else:
            # the ONE default sentence, computed in export_json.py for every surface
            t = TEXTE.get("aufbewahrung_standard") or {}
            refs = " · ".join(f"SHR {r[0]} {r[1]}" for r in (t.get("refs") or []) if isinstance(r, (list, tuple)) and len(r) >= 2)
            h.append("<h3>Aufbewahrung / Löschung</h3><div class='small muted'>"
                     + (esc(t["text"]) + (f" <span class='mono'>Belege: {esc(refs)}</span>" if refs else "") if t.get("text")
                        else "keine sektorale Frist erfasst — die Standardregel ist im Export nicht hinterlegt (offen)")
                     + "</div>")
        sd = f.get("standard_divergenzen") or {}
        ang, feh = sd.get("angleichen") or [], sd.get("fehlend") or []
        bz = sd.get("bezeichnungen") or []
        if ang or feh or bz:
            nang = sd.get("n_angleichen", sum(1 for i in ang if i["art"] != "pflicht_uneinheitlich"))
            nunk = sd.get("n_pflicht_ungeklaert", sum(1 for i in ang if i["art"] == "pflicht_uneinheitlich"))
            nfeh = sd.get("n_fehlend", 0)
            parts = []
            if nang: parts.append(f"{nang} anzugleichen")
            if nunk: parts.append(f"{nunk} Pflicht im Korpus ungeklärt")
            if feh and nfeh: parts.append(pl(nfeh, "Punkt", "Punkte") + " ohne Standard")
            h.append(f"<h3>Standard-Divergenzen{(' (' + ' · '.join(parts) + ')') if parts else ''}</h3>"
                     + "<div class='small muted'>Was dieses Formular davon trennt, Teil eines einheitlichen "
                       "Datenstandards zu sein: oben dasselbe Datum anders verlangt als anderswo, unten Daten "
                       "ohne zitierbaren Standard.</div>")
            if ang:
                h.append("<table><thead><tr><th>Datenfeld</th><th>Art</th><th>hier</th>"
                         "<th>sonst im Korpus</th><th>Rechtsgrundlage hier</th></tr></thead><tbody>")
                for i in ang:
                    h.append(f"<tr><td><b>{esc(i['feld'])}</b>"
                             + (f" › {esc(i['teilfeld'])}" if i.get("teilfeld") else "")
                             + f"<div class='mono'>{esc(i.get('standard'))} {esc(i.get('element'))}</div></td>"
                             f"<td class='small'>{esc(render_label(LABELS.DIV, i['art']))}</td>"
                             f"<td class='small'><span class='b warn'>{esc(i['hier'])}</span></td>"
                             f"<td class='small'>{esc(i['andere'])}</td>"
                             f"<td class='small'>{esc(i.get('basis') or '')}</td></tr>"
                             f"<tr><td colspan='5' class='small muted'>→ {esc(i['aktion'])}</td></tr>")
                h.append("</tbody></table>")
            var = [i for i in bz if i["klasse"] == "variante"]
            auf = [i for i in bz if i["klasse"] == "pruefen" and i.get("pruefart") == "aufteilen"]
            zuo = [i for i in bz if i["klasse"] == "pruefen" and i.get("pruefart") != "aufteilen"]
            if var:
                h.append("<div class='small' style='margin:6px 0'><b>Bezeichnung angleichen</b> — gleiches Datum, anderer Name: "
                         + " · ".join(f"«{esc(i['hier'])}» → <b>«{esc(i['vorschlag'])}»</b>" for i in var) + "</div>")
            if auf:
                h.append("<div class='small' style='margin:6px 0'><b>Feld bündelt mehrere Daten — aufteilen:</b> "
                         + " · ".join(f"«{esc(i['hier'])}»" for i in auf) + "</div>")
            if zuo:
                h.append("<div class='small muted' style='margin:6px 0'><b>eCH-Zuordnung korrigieren</b> (Aufgabe der Databank, nicht des Formulars): "
                         + " · ".join(f"«{esc(i['hier'])}» ≠ {esc(i.get('standard'))} {esc(i.get('element'))}" for i in zuo) + "</div>")
            if feh:
                h.append("<div class='small'>" + " ".join(
                    f"<div>• <b>{esc(render_label(LABELS.DIV, i['art']))}</b>"
                    + (f" ({esc(i['standard'])})" if i.get("standard") else "")
                    + f": {pl(i['n'], 'Datenpunkt', 'Datenpunkte')} — {esc(' · '.join(i['felder']))}"
                    + ("…" if i["n"] > len(i["felder"]) else "")
                    + f"<div class='muted'>→ {esc(i['aktion'])}</div></div>"
                    for i in feh) + "</div>")
        h.append("<h3>Handlungsbedarf</h3><div class='small'>" + todo_html(f) + "</div></div>")
    if not forms:
        h.append(formless_html(s, dv))
    h.append(legend_html())
    h.append(foot_html() + "</body></html>")
    return "\n".join(h)


def main():
    global STAND, TEXTE, DATENSTAND, ZITATE
    pdf = "--pdf" in sys.argv
    only = None
    if "--only" in sys.argv:
        only = int(sys.argv[sys.argv.index("--only") + 1])
    D = json.load(open(os.path.join(ROOT, "data_export.json"), encoding="utf-8"))
    STAND = (D.get("generated_at") or "")[:10]
    TEXTE = D.get("texte") or {}
    DATENSTAND = D.get("datenstand") or {}
    ZITATE = D.get("zitate") or {}
    for l in D.get("laws", []):
        s = (l.get("short_title") or "").strip()
        if 2 <= len(s) <= 24 and ";" not in s:
            LAWJUR[s.lower()] = l.get("jurisdiction_level")
    dst = {d["name"]: d for d in D.get("dienststellen", [])}
    by_svc = {}
    for f in D["forms"]:
        by_svc.setdefault(f["service_id"], []).append(f)
    os.makedirs(OUT, exist_ok=True)
    index = []
    n = 0
    for s in sorted(D["services"], key=lambda x: (x.get("department") or "", x["name"])):
        if only and s["id"] != only:
            continue
        slug = re.sub(r"[^a-z0-9]+", "-", (s.get("slug") or s["name"]).lower()).strip("-")[:80] or f"service-{s['id']}"
        page = dossier(s, by_svc.get(s["id"], []), dst.get(s.get("dienststelle")))
        open(os.path.join(OUT, slug + ".html"), "w", encoding="utf-8").write(page)
        index.append((s, slug, len(by_svc.get(s["id"], []))))
        n += 1
        if pdf and os.path.exists(CHROME):
            subprocess.run([CHROME, "--headless=new", "--disable-gpu", "--no-pdf-header-footer",
                            f"--print-to-pdf={os.path.join(OUT, slug + '.pdf')}",
                            "file://" + os.path.join(OUT, slug + ".html")],
                           capture_output=True, timeout=120)
    if not only:
        # the PDF column only when at least one PDF exists (an always-empty
        # column reads as a rendering error)
        pdf_any = any(os.path.exists(os.path.join(OUT, slug + ".pdf")) for _, slug, _ in index)
        rows = "".join(f"<tr><td>{esc(s.get('department') or '')}</td><td><a href='{slug}.html'>{esc(s['name'])}</a></td>"
                       f"<td>{esc(s.get('dienststelle') or '')}</td><td>{nf}</td>"
                       + (f"<td>{('<a href=' + chr(39) + slug + '.pdf' + chr(39) + '>PDF</a>') if os.path.exists(os.path.join(OUT, slug + '.pdf')) else ''}</td>" if pdf_any else "")
                       + "</tr>"
                       for s, slug, nf in index)
        filt = ("<input class='filter' type='search' placeholder='Filter: Departement, Service oder Dienststelle …' "
                "oninput=\"for(const r of document.querySelectorAll('tbody tr'))r.hidden=!r.textContent.toLowerCase().includes(this.value.toLowerCase())\">")
        # marker a locally opened dashboard.html probes for: present = the whole
        # repository sits next to it (dossier/Formular/flow links work offline);
        # missing = a single saved copy, whose repository links then open online
        open(os.path.join(OUT, "_repo.js"), "w", encoding="utf-8").write(
            "/* GENERATED by scripts/export_dossiers.py - marker: the repository is present */\nwindow.__cgRepo=true;\n")
        open(os.path.join(OUT, "index.html"), "w", encoding="utf-8").write(
            GENERATED + "\n"
            f"<!DOCTYPE html><html lang='de'><head><meta charset='utf-8'><link rel='icon' href='data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 32 32%27%3E%3Crect width=%2732%27 height=%2732%27 rx=%277%27 fill=%27%23e8b100%27/%3E%3C/svg%3E'><title>Datenschutz-Dossiers</title><style>{CSS}</style></head><body>"
            f"<h1>Datenschutz-Dossiers je Service</h1>"
            f"<div class='sub'><a href='../dashboard.html'>Dashboard</a> · {n} Services · Stand {fmt_date(STAND)} · ein bis wenige A4-Seiten je Service, druckbar</div>"
            "<div class='small' style='margin:6px 0'>Jedes Dossier zeigt für einen Service: Dienststelle und Kontakt, DVSH-Status, "
            "Rechtsgrundlagen, Ergebnis des Verfahrens und Rechtsmittel, je Formular die verlangten Daten mit Pflicht, eCH-Element, "
            "Rechtsgrundlage und Kennzeichen (⛨, ↺), Beilagen mit Halter, Empfänger, Aufbewahrung, Standard-Divergenzen und den "
            "Handlungsbedarf. Alle Seiten werden aus citygov.db (über data_export.json) erzeugt; «zu ermitteln» und «offen» "
            "bezeichnen Wissenslücken der Databank, keine festgestellten Verstösse.</div>"
            + filt +
            f"<table><thead><tr><th>Departement</th><th>Service</th><th>Dienststelle</th><th>Formulare</th>{'<th>PDF</th>' if pdf_any else ''}</tr></thead><tbody>{rows}</tbody></table>"
            f"<div class='foot'>Datenstand: Export {fmt_date(STAND)}"
            f"{(' · DVSH-Stand ' + esc(fmt_date(DATENSTAND['dvsh_stand']))) if DATENSTAND.get('dvsh_stand') else ''}.</div></body></html>")
    print(f"dossiers: {n} HTML" + (" + PDF" if pdf else "") + f" in {OUT}")


if __name__ == "__main__":
    main()
