#!/usr/bin/env python3
"""One Datenschutz-Dossier per service, as a small self-contained HTML page
(dossiers/<slug>.html) and - with --pdf and a local Chrome - as PDF.

Why: a Dienststelle should get its own picture on one to four A4 pages (longer
where a Formular has many Standard-Divergenzen) without opening the dashboard
(the whole databank in one large page). Everything on the page comes from
data_export.json, i.e. from citygov.db, and says what it is: verified,
curated, derived or open. Nothing
here is a new judgment: the labels come from scripts/labels.py, the
Handlungsbedarf from export_json.py (form.handlungsbedarf), the default
retention sentence from data.texte - the same places the dashboard reads.

Contents: Service (Dienststelle, Kontakt aus dem DVSH, DVSH-Status, Zweck),
Rechtsgrundlagen des Services, Verfahrens-Ergebnis und Rechtsmittel, je
Formular: Kanal/Unterschrift/Bürgerlast, die Datenfelder (Pflicht, eCH-Element
und Datentyp, Grundlage, ⛨, ↺), Beilagen mit Halter, Empfänger mit Artikel,
Aufbewahrung, Standard-Divergenzen und der Handlungsbedarf des Formulars; on
top, the Handlungsbedarf of the whole service by priority tier (data standard
first). The data-standard tier includes the data points without an eCH
standard in force (form.handlungsbedarf category «kein_standard»: no eCH
standard, or one still «In Arbeit») — the largest data-standard gap.
Open points are GAPS still to close, never framed as a risk.

One status language with the dashboard: every status badge takes one of the
four tones of DATA.labels.ton through DATA.labels.ton_map / ton_of_art — the
colour says who acts next (st-ok geklärt · st-act Dienststelle · st-dec Kanton ·
st-open Databank) — and a symbol, so the tones stay apart in a black-and-white
print: a status is always tone + word + symbol. The eCH state of a data point and
the answer to its legal question are read from the export (ech_state, basis_state),
never worked out a second time here. Markers (⛨, ↺, Rechtsebene) are neutral
outlines, never a tone; the eSH draft is violet and dashed, as in the dashboard.
Colours, font and text sizes come from scripts/theme.py. A printed legend explains
tones and glyphs, the footer states the Datenstand.

The contact reads as in the dashboard: «Kontakt (laut DVSH): Adresse · Tel. … ·
E-Mail …», telephone and e-mail as links. The stored values stay as the DVSH
delivers them; only the target of a tel: link is put into the international form.

Escaping: every value from the export passes esc() on its way into the page (text
and attribute values alike), a link target passes web_href() / page_href() /
kontakt_html(). The pages inline no JSON.

With --pdf the PDFs land next to the HTML pages and dossiers/index.html gets a
PDF column; without --pdf the index never links a PDF, even if one from an
earlier --pdf run is still on disk (the PDFs are local, not published).
Also writes dossiers/_repo.js, the marker a locally opened dashboard.html
probes for to know the whole repository sits next to it.

    python3 scripts/export_dossiers.py [--pdf] [--only <service_id>]
"""
import html, json, os, re, subprocess, sys, urllib.parse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import labels as LABELS
import theme as THEME
from common import dossier_slug
from labels import fmt_date, pl, render_label
# the dashboard's wording pass over texts from the export (plain words instead of
# «Over-collection», «Korpus»; counts with their unit) — one list for both surfaces
from build_dashboard import gap_wording

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dossiers")
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
GENERATED = ("<!-- GENERATED by scripts/export_dossiers.py from citygov.db via data_export.json "
             "— do not edit; run python3 scripts/export_dossiers.py -->")

# favicon (the crest's gold) and the viewport line — both page types carry them
HEAD = THEME.VIEWPORT + THEME.favicon()

# filled in main() from data_export.json: the DATA date (ISO, printed through
# labels.fmt_date like every date on the dashboard) and the data's own
# provenance, never the render date
STAND = ""
TEXTE = {}
DATENSTAND = {}
ZITATE = {}
# DATA.labels (data_export.json) — tones, priority tiers and Handlungsbedarf
# wording are read from there, the same mapping the dashboard uses
LAB = {}
TODO = {}


def esc(s):
    """A value on its way into the page — as text or inside a quoted attribute
    (& < > " ' are written as entities). Every value from the export passes here."""
    return html.escape(str(s if s is not None else ""), quote=True)


def web_href(url):
    """A link target taken from the data (DVSH, eCH): only an http(s) address becomes
    a link. Anything else — «www.…» without a scheme, javascript:, «<UNKNOWN>» —
    returns "" and the caller prints plain text."""
    url = str(url or "").strip()
    return esc(url) if re.match(r"https?://\S+$", url, re.I) else ""


def page_href(path, fragment=""):
    """A page of this repository as link target (dossier, PDF, dashboard route): the
    path percent-encoded, then escaped for the attribute."""
    return esc(urllib.parse.quote(str(path), safe="/.-_~")
               + ("#" + urllib.parse.quote(str(fragment), safe="/.-_~") if fragment else ""))


def code_name(s):
    """An eCH element or type name on its way into the page. A very long camelCase name
    («applicationForCreditingForeign…», 76 characters) gets break opportunities (<wbr>)
    at its word boundaries, so it cannot push a table wider than the page; the name
    itself is unchanged."""
    s = str(s if s is not None else "")
    if len(s) < 40:
        return esc(s)
    return "<wbr>".join(esc(p) for p in re.split(r"(?<=[a-z0-9])(?=[A-Z])", s))


# ---- the contact line: one wording with the dashboard (kontaktHtml) -----------
# «Kontakt (laut DVSH): Adresse · Tel. +41 52 … · E-Mail …» — address first, then
# telephone, then e-mail, each named; without a contact «nicht hinterlegt». The parts
# are printed as the DVSH stores them — a number or an address is never rewritten;
# telephone and e-mail are links, and only the TARGET of a tel: link is put into the
# international form. Tests and order are the dashboard's (build_dashboard.py,
# kontaktHtml) and the guided forms' (build_flows.py); the words («Kontakt (laut
# DVSH)», «Tel.», «E-Mail», «nicht hinterlegt») are labels.KONTAKT, read by all three.
KONTAKT_LABEL = LABELS.KONTAKT["label"] + ":"
KONTAKT_LEER = LABELS.KONTAKT["leer"]
MAIL_RX = re.compile(r"[^\s@]+@[^\s@]+\.[a-z]{2,}$", re.I)
TEL_RX = re.compile(r"\+?[\d\s()/.-]+$")


def tel_target(p):
    """«052 632 74 66» -> «+41526327466»: what a tel: link dials, in international
    form (a number with the Swiss trunk 0 gets +41; «+41 (0)52 …» loses the (0))."""
    d = re.sub(r"[^\d+]", "", p.replace("(0)", ""))
    if d.startswith("00"):
        return "+" + d[2:]
    if d.startswith("0"):
        return "+41" + d[1:]
    return d


def kontakt_parts(k):
    """The stored contact as [(kind, text)], kind ∈ mail · tel · text, in stored order.
    An entry that holds several parts («a@sh.ch · Strasse 1») is split at « · »."""
    out = []
    for x in k or []:
        for p in str(x or "").split(" · "):
            p = p.strip()
            if not p:
                continue
            if MAIL_RX.match(p):
                out.append(("mail", p))
            elif TEL_RX.match(p) and len(re.findall(r"\d", p)) >= 9:
                out.append(("tel", p))
            else:
                out.append(("text", p))
    return out


def kontakt_html(k):
    """The whole contact line: «<b>Kontakt (laut DVSH):</b> Adresse · Tel. <link> ·
    E-Mail <link>»; a Dienststelle without a contact in the DVSH reads «nicht hinterlegt»."""
    adr, tel, mail = [], [], []
    for kind, p in kontakt_parts(k):
        if kind == "mail":
            # the stored address, HTML-escaped — the same target as the dashboard's and the
            # guided forms' kontaktHtml write (one rule, three renderers)
            mail.append(f'{esc(LABELS.KONTAKT["mail"])} <a href="mailto:{esc(p)}">{esc(p)}</a>')
        elif kind == "tel":
            tel.append(f'{esc(LABELS.KONTAKT["tel"])}\u00a0<a class="nw" href="tel:{esc(tel_target(p))}">{esc(p)}</a>')
        else:
            adr.append(esc(p))
    parts = adr + tel + mail
    return (f"<b>{esc(KONTAKT_LABEL)}</b> "
            + (" · ".join(parts) if parts else f'<span class="muted">{esc(KONTAKT_LEER)}</span>'))


# ---- one status language: the colour says who acts next ---------------------
# The four tones of DATA.labels.ton. The symbol (drawn by the CSS before the
# badge text) keeps them apart in a black-and-white print; the legend maps
# colour, symbol and who acts. The symbols are set in scripts/theme.py.
TON_SYM = THEME.TON_SYM


def ton_of(domain, code):
    """Tone of a status code via DATA.labels.ton_map — the dashboard's mapping.
    A code without an entry is grey (not yet settled), never green."""
    t = ((LAB.get("ton_map") or {}).get(domain) or {}).get(code)
    return t if t in TON_SYM else "open"


def cat_ton(cat):
    """Tone of a Handlungsbedarf category: its kind (todo_cats) via ton_of_art."""
    c = TODO.get(cat)
    t = (LAB.get("ton_of_art") or {}).get(c[3]) if c else None
    return t if t in TON_SYM else "open"


def item_ton(it):
    """A Handlungsbedarf item carries its tone from export_json; else its category's."""
    return it["ton"] if it.get("ton") in TON_SYM else cat_ton(it.get("cat"))


def item_stufe(it):
    """Priority tier of an item (DATA.labels.stufe_of_cat); unknown -> last tier."""
    return it.get("stufe") or (LAB.get("stufe_of_cat") or {}).get(it.get("cat")) or 4


def first_tier():
    """The data-standard tier — the first of DATA.labels.stufen, which leads."""
    return ((LAB.get("stufen") or [[1]])[0])[0]


# thousands grouped as the dashboard's nf() (de-CH: 2'900)
nf = lambda n: f"{int(n or 0):,}".replace(",", "'")


def form_items(f):
    """form.handlungsbedarf — it carries the data-standard gaps itself (category
    «kein_standard», export_json), so the dossier counts exactly like the board."""
    return list(f.get("handlungsbedarf") or [])


# what the number of a Handlungsbedarf category counts (export_json.handlungsbedarf):
# fields, data points or pairs of Formulare. None = one point per Formular, so
# the chip carries no number and the Formulare are counted instead. A category
# missing here shows its bare number.
UNIT = LABELS.EINHEIT          # shared with the dashboard (labels.py)


def count_txt(cat, n):
    """«: 55 Datenpunkte» after a category label; empty for a per-Formular point."""
    u = UNIT.get(cat)
    if u is None:                 # counted per Formular: the chip carries no number
        return ""
    return f": {nf(n)}" + (f" {u[0] if n == 1 else u[1]}" if u[0] else "")


def stufe_of(nr):
    """(«1 · Datenstandard», explanation) for a tier number of DATA.labels.stufen."""
    for x in LAB.get("stufen") or []:
        if x[0] == nr:
            return f"{x[0]} · {x[1]}", (x[2] if len(x) > 2 else "")
    return f"Stufe {nr}", ""


def ton_label(t):
    return ((LAB.get("ton") or {}).get(t) or {}).get("label") or t


def ton_short(t):
    """«geklärt» / «Dienststelle» / «Kanton» / «Databank» — who acts, in one word."""
    lb = ton_label(t)
    return lb if t == "ok" else lb.split()[0]


def st(t, inner, short=False):
    """One status badge in tone t. inner is ready HTML; the title names who acts
    next and what that means (DATA.labels.ton) — only who acts where the badge
    repeats by the hundred (index)."""
    if t not in TON_SYM:          # an unknown tone is «not yet settled», never a class of its own
        t = "open"
    x = (LAB.get("ton") or {}).get(t) or {}
    tip = " — ".join(v for v in (x.get("label"), None if short else x.get("bedeutung")) if v)
    return f'<span class="b st-{t}" title="{esc(tip)}">{inner}</span>'


def ton_key_html():
    """The four tones in one line — dossier head, legend and index say it alike."""
    parts = " · ".join(f"{esc(((LAB.get('ton') or {}).get(t) or {}).get('farbe') or '')} {st(t, esc(ton_short(t)))}"
                       for t in ("ok", "act", "dec", "open"))
    return (f"<div class='key'><b>Die Farbe sagt, wer als Nächstes handelt:</b> {parts} — grau ist eine "
            "Hausaufgabe der Databank, kein Befund über die Verwaltung.</div>")
# gesetzesebenen -> wording of the Rechtsmittel line; mirrors the inline literal in
# build_dashboard.py (rechtsmittelLine) and belongs in labels.py with the other maps —
# labels.JUR says «Bund/Kanton/Gemeinde», which is not the same sentence, so it is
# kept here until labels.py carries it for both surfaces
EBENE = LABELS.EBENE          # level of law, sentence form — shared with the dashboard

# The look comes from scripts/theme.py (THEME.css_root(): colours, the system font, the six
# text sizes — px on screen, pt on paper). The dossier keeps its white page and its compact
# print layout; it only stops using values of its own.
CSS = THEME.css_root(compact=True) + """
@page{size:A4;margin:14mm 14mm 16mm}
*{box-sizing:border-box}
:root{color-scheme:light only}
/* overflow-wrap: a word longer than the line («Sicherheitsbeleuchtung/Sicherheitsstromversorgungen»
   on a phone) breaks instead of making the page scroll sideways */
body{font:var(--fs-m)/1.35 var(--font);color:var(--ink);background:var(--card);margin:0;padding:18px 22px;max-width:900px;overflow-wrap:break-word}
h1{font-size:var(--fs-xl);line-height:1.2;margin:0 0 2px}h2{font-size:var(--fs-l);margin:14px 0 4px;border-bottom:1px solid var(--line-strong);padding-bottom:2px}
h3{font-size:var(--fs-m);margin:10px 0 3px}
.sub{color:var(--ink-faint);font-size:var(--fs-s)}.muted{color:var(--ink-faint)}.small{font-size:var(--fs-s)}
a{color:var(--link);text-underline-offset:2px}a:hover{text-decoration:none}a.b{text-decoration:none}
table{border-collapse:collapse;width:100%;font-size:var(--fs-s)}th,td{text-align:left;vertical-align:top;padding:2px 5px;border-bottom:1px solid var(--line)}
th{font-weight:600;color:var(--ink-faint);font-size:var(--fs-xs);text-transform:uppercase;letter-spacing:.03em}
/* a badge is one box; a long one may wrap inside it, so no table is pushed wider than the page */
.b{display:inline-block;border:1px solid var(--line-strong);border-radius:4px;padding:0 4px;font-size:var(--fs-xs)}
.b{-webkit-print-color-adjust:exact;print-color-adjust:exact}
/* status badge: tint, border and the tone as text from the theme; the border style
   (solid · solid · double · dashed) and the symbol keep the tones apart without colour */
.b.st-ok{color:var(--ton-ok-ink);background:var(--ton-ok-bg);border-color:var(--ton-ok-line)}
.b.st-act{color:var(--ton-act-ink);background:var(--ton-act-bg);border-color:var(--ton-act-line)}
.b.st-dec{color:var(--ton-dec-ink);background:var(--ton-dec-bg);border-color:var(--ton-dec-line);border-style:double;border-width:3px;padding:0 3px}
.b.st-open{color:var(--ton-open-ink);background:var(--ton-open-bg);border-color:var(--ton-open-line);border-style:dashed}
.b.mk{color:var(--ink);background:var(--card);border-color:var(--line-dark)}
/* the eSH code is a draft of the canton, never official eCH: violet, dashed — as in the dashboard */
.b.esh{color:var(--esh);background:var(--esh-bg);border:1px dashed var(--esh-line)}
.key{font-size:var(--fs-xs);color:var(--ink-faint);margin:3px 0}
.prio th{width:30%;text-transform:none;letter-spacing:0;font-size:var(--fs-s);color:var(--ink);white-space:nowrap}
.prio td .b{margin:1px 0}
.nw,.nw .b{white-space:nowrap}
/* the list of all dossiers has six columns: a wider page than the A4-shaped dossier */
body.idx{max-width:1080px}
.tier{font-weight:600;font-size:var(--fs-xs);color:var(--ink-faint);margin:5px 0 1px}
.mono{font-family:var(--mono);font-size:var(--fs-xs)}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:6px 18px}
.box{border:1px solid var(--line-strong);border-radius:6px;padding:6px 9px;margin:6px 0}
.print{position:fixed;right:14px;top:10px;border:1px solid var(--line-strong);background:var(--card);color:var(--ink);border-radius:6px;padding:5px 10px;font:inherit;cursor:pointer}
.nav{font-size:var(--fs-s);margin:0 0 8px}.nav a{margin-right:12px}
.todo,.gap2{margin:2px 0}.gap4{margin-top:4px}.gap6{margin:6px 0}
/* the word of a count chip (index): read out, not drawn — the legend above the table shows it.
   The chip is its containing block, so the hidden word scrolls with the table on a phone */
.nw .b{position:relative}
.vh{position:absolute;width:1px;height:1px;margin:-1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
.legend{margin-top:12px;font-size:var(--fs-xs);color:var(--ink-faint);border-top:1px dashed var(--line-strong);padding-top:4px}
.foot{margin-top:10px;font-size:var(--fs-xs);color:var(--ink-faint);border-top:1px solid var(--line-strong);padding-top:4px}
input.filter{font:inherit;color:var(--ink);padding:4px 8px;border:1px solid var(--line-strong);border-radius:6px;margin:8px 0;width:360px;max-width:100%}
input.filter:focus-visible{outline:2px solid var(--link);outline-offset:1px}
/* a phone or a narrow window: the page keeps its width, a wide table scrolls on its own */
@media screen and (max-width:700px){body{padding:12px 14px}.print{position:static;margin:0 0 8px}.grid{grid-template-columns:1fr}
table{display:block;overflow-x:auto}.prio th{white-space:normal;width:auto}}
@media print{.print,.nav,input.filter{display:none}.prio tr{break-inside:avoid}body{padding:0}h2,h3{break-after:avoid}tr{break-inside:avoid}thead{display:table-header-group}
a{color:inherit;text-decoration:none}a[href^=http]::after{content:' (' attr(href) ')';font-size:var(--fs-xs);color:var(--ink-faint)}}
"""
# the tone symbol before every status badge — from THEME.TON_SYM, the one place it is
# set; with the border (solid · solid · double · dashed) it keeps the four tones
# apart in a black-and-white print
CSS += ("".join(f'.b.st-{t}::before{{content:"{sym}\\00a0"}}' for t, sym in TON_SYM.items())
        + ",".join(f".b.st-{t}::before" for t in TON_SYM) + "{font-weight:700;font-size:1.2em;line-height:1}\n")   # theme:keep — the symbol scales with the badge it sits in


# short title -> jurisdiction, filled from the law table in main(); used to read
# the level of a DVSH legal reference instead of trusting the list it sits in
LAWJUR = {}


def abbrs_of(label):
    """Every candidate short title in a free-text reference: each parenthesised
    abbreviation plus the trailing token ("Art. 3 GesG" -> GesG)."""
    out = [m.group(1) for m in re.finditer(r"\(([^)]{2,24})\)", label or "")]
    parts = (label or "").strip().split()
    if parts:
        out.append(parts[-1])
    return out


def jur_of_ref(x, label, local=None):
    """Bund / Kanton / Ebene offen for one free-text DVSH legal reference.

    The modeller's «recht_bund» list is free text ("Art. 3 GesG", a rechtsbuch
    link, a title) and regularly holds CANTONAL law, so the level is read from
    evidence only: the URL host, an SR/SHR marker, a short title the databank
    knows, or the titled entry in the SAME list that shares the abbreviation.
    Nothing is assumed.
    """
    url = x.get("url") or ""
    if "rechtsbuch.sh.ch" in url or re.search(r"\bSHR\b", label) or re.match(r"(?i)kantonale?s?\b", label):
        return "Kanton"
    if (re.search(r"(^|\.)admin\.ch", url) or re.search(r"\bSR\s?\d", label)
            or re.match(r"(?i)(bundesgesetz|bundesverfassung|bundesbeschluss|bundesratsbeschluss)\b", label)):
        return "Bund"
    if re.match(r"(?i)(interkantonale?s?|konkordat)\b", label):
        return "interkantonal"
    for a in abbrs_of(label):
        j = LABELS.JUR.get(LAWJUR.get(a.lower())) or (local or {}).get(a.lower())
        if j:
            return j
    return "Ebene offen"


def cut(s, n=300):
    """Truncate at the last space before n characters and mark the cut — a legal
    quote never ends mid-word."""
    s = (s or "").strip()
    if len(s) <= n:
        return s
    head = s[:n]
    sp = head.rfind(" ")
    return (head[:sp] if sp > n // 2 else head).rstrip(" ,;·") + " …"


def basis_label(d):
    """The answer to the legal question of one Datenfeld as a status badge. WHICH
    answer it is comes from the export (basis_state, a key of ton_map.basis); this
    function only words it."""
    bs = d.get("basis_state")
    if bs == "artikel" and d.get("legal_basis"):
        b = d["legal_basis"][0]
        nr = b.get("sr_number") or b.get("cantonal_ref") or ""
        lc = b.get("last_checked") or ""
        # the proof level of the citation as the ingest scripts set it: a federal
        # article read from the official Fedlex text ('verified'), or an article
        # read from the official law PDF ('Gesetze-PDF …'). The basis itself is
        # «artikel» (geklärt); an unverified quote still leaves the Databank a
        # check to do, so the badge takes the tone of the proof level
        if lc == "verified":
            prov, lv = "verifiziert (Fedlex)", "verified"
        elif lc.startswith("Gesetze-PDF"):
            prov, lv = ("Quelle SHR-PDF" if b.get("jurisdiction") == "cantonal" else "Quelle Gesetzes-PDF"), "quelle_pdf"
        else:
            prov, lv = "Zitat nicht verifiziert", "unverifiziert"
        return (st(ton_of("verif", lv), f'{esc(b.get("article_no"))} {esc((b.get("law_short") or "").strip())}'
                      f'{(" · " + esc(nr)) if nr else ""}') + f' <span class="small muted">{esc(prov)}</span>')
    if bs == "art5_offen":
        # a besonders schützenswerte Angabe judged «aufgabe»: KDSG Art. 4 Abs. 1
        # lit. b is not enough, Art. 5 Abs. 1 lit. a or b must be named -> OPEN
        return st(ton_of("basis", bs), "aufgabennotwendig — Grundlage nach KDSG Art. 5 Abs. 1 noch nicht benannt")
    if bs == "aufgabe":
        return st(ton_of("basis", bs), f'{esc(render_label(LABELS.BASIS_TYP, bs))} (KDSG Art. 4 Abs. 1 lit. b) — keine explizite Norm')
    if bs == "ohne":
        return st(ton_of("basis", bs), f'{esc(render_label(LABELS.BASIS_TYP, bs))} — weder Norm noch Aufgabenbedarf')
    if bs == "offen":
        return st(ton_of("basis", bs), f'{esc(render_label(LABELS.BASIS_TYP, bs))} — keine explizite Norm')
    return st(ton_of("basis", "zu_ermitteln"), "Rechtsgrundlage zu ermitteln")


# the status of a standard that is not in force -> the eCH state it stands for: still
# in the making (the canton decides meanwhile, amber) or no longer in force (the
# databank replaces the mapping, grey) — the dashboard's ECH_STD_STATE
STD_STATE = {"In Arbeit": "standard_entwurf", "Sistiert": "standard_alt",
             "Aufgehoben": "standard_alt", "Abgelöst": "standard_alt"}


def std_badge(e):
    """The standard's own status when it is not in force (Sistiert, In Arbeit …), in
    the tone of the state it stands for; a status without one is grey."""
    return (" " + st(ton_of("ech", STD_STATE.get(e["status"])), esc(e["status"]))
            if e.get("status") and e["status"] != "Genehmigt" else "")


def ech_state(u):
    """eCH state of one Datenfeld or Teilfeld — the key export_json stamped on it
    (ech_state, a key of ton_map.ech). ONE classification: the figures count it, the
    dashboard draws it, the dossier words it; nothing is derived here."""
    return u.get("ech_state") or "ungeprueft"


# the order of the sub-field chips: settled first, then who acts (Kanton, Databank)
STATE_ORDER = ("element", "standard_ohne_elemente", "standard_entwurf", "kein_standard",
               "zuordnung_falsch", "standard_alt", "element_offen", "ungeprueft")


def state_label(code):
    """Reader's word for an eCH state: labels.DIV; the settled element and the mapping
    the databank corrects (the Handlungsbedarf category «zuordnung») have their own."""
    if code == "element":
        return "eCH-Element"
    if code == "zuordnung_falsch":
        return todo_label("zuordnung")
    return render_label(LAB.get("div") or LABELS.DIV, code)


def own_ech(d):
    """What the Databank mapped to ONE data point — a field without sub-fields —
    as a tone badge (ton_map.ech) plus the standard's status where not in force."""
    e = d.get("ech") or {}
    state = ech_state(d)
    stb = std_badge(e)
    if state == "zuordnung_falsch":
        # an element is assigned, but the label means another piece of data: the
        # databank corrects its own mapping — grey, never shown as settled
        return (st(ton_of("ech", state), f'<span class="mono">{esc(e.get("standard"))} {code_name(e.get("element"))}</span>'
                                         f' · {esc(state_label(state))}') + stb)
    if state == "element":
        return (st(ton_of("ech", state), f'<span class="mono">{esc(e.get("standard"))} {code_name(e.get("element"))}</span>')
                + (f' <span class="mono muted">⟨{code_name(e["datatype"])}⟩</span>' if e.get("datatype") else "") + stb)
    if state in ("standard_entwurf", "standard_alt"):
        # a standard not in force: the mapping cannot be cited — still in the making
        # (the canton decides meanwhile) or no longer in force (the databank replaces
        # it by the successor); the status is the badge's own text
        return st(ton_of("ech", state), f'<span class="mono">{esc(e.get("standard"))}</span> · {esc(e.get("status"))}')
    if state in ("element_offen", "standard_ohne_elemente"):
        # an element is only owed where the databank holds an element catalogue
        # for the standard; without one (process/FHIR standard or XSD not swept)
        # the mapping stays on standard level — labels.DIV words it
        note = "Element offen" if state == "element_offen" else render_label(LABELS.DIV, state)
        return st(ton_of("ech", state), f'<span class="mono">{esc(e.get("standard"))}</span> · {esc(note)}') + stb
    if state == "kein_standard":
        return (st(ton_of("ech", state), "kein eCH-Standard")
                + (f' <span class="b esh">{esc(d["esh"].get("code"))} Entwurf (eSH)</span>' if d.get("esh") else ""))
    return st(ton_of("ech", "ungeprueft"), "nicht geprüft")


def parent_ech(d):
    """The composite field's own mapping as plain muted text — never a tone: the
    unit of the data standard is the sub-field, so the parent's mapping says
    nothing about whether its data points are settled."""
    e = d.get("ech") or {}
    if e.get("element"):
        txt = (f'<span class="mono">{esc(e.get("standard"))} {code_name(e["element"])}</span>'
               + (f' <span class="mono">⟨{code_name(e["datatype"])}⟩</span>' if e.get("datatype") else ""))
    elif e.get("standard"):
        note = (e["status"] if e.get("status") in STD_STATE
                else ("Element offen" if e.get("n_elements") else render_label(LABELS.DIV, "standard_ohne_elemente")))
        txt = f'<span class="mono">{esc(e["standard"])}</span> · {esc(note)}'
    elif d.get("ech_status") == "kein_standard":
        txt = "kein eCH-Standard" + (f' <span class="b esh">{esc(d["esh"].get("code"))} Entwurf (eSH)</span>' if d.get("esh") else "")
    else:
        return ""
    return f'<div class="small muted">Feld als Ganzes: {txt}</div>'


def ech_cell(d):
    subs = [s for s in (d.get("subfields") or []) if isinstance(s, dict)]
    if not subs:
        return own_ech(d)
    # a composite: the tone comes from its sub-fields, one chip per eCH state
    # (ton_map.ech), counted — the same units export_json counts
    by = {}
    for s in subs:
        by.setdefault(ech_state(s), []).append(s)
    chips = []
    for code in sorted(by, key=lambda c: STATE_ORDER.index(c) if c in STATE_ORDER else 99):
        us = by[code]
        lb = state_label(code)
        extra = ""
        if code in ("standard_entwurf", "standard_alt"):
            # which standard, in which status (Sistiert, In Arbeit …)
            seen = []
            for u in us:
                k = f'{(u.get("ech") or {}).get("standard") or ""} {(u.get("ech") or {}).get("status") or ""}'.strip()
                if k not in seen:
                    seen.append(k)
            extra = " · " + ", ".join(seen)
        chips.append(st(ton_of("ech", code), f"{esc(lb)}: {esc(len(us))}{esc(extra)}"))
    # an element-mapped sub-field whose standard is itself not approved keeps
    # the status badge a single field shows (std_badge)
    stat = []
    for u in by.get("element", []):
        b = std_badge(u.get("ech") or {})
        if b and b not in stat:
            stat.append(b)
    stds = []
    for u in by.get("element", []):
        if (u.get("ech") or {}).get("standard") and u["ech"]["standard"] not in stds:
            stds.append(u["ech"]["standard"])
    return (f'<div class="small">{esc(pl(len(subs), "Teilfeld", "Teilfelder"))} — ' + " ".join(chips) + "".join(stat)
            + (f' <span class="muted">({esc(", ".join(stds[:4]))}{"…" if len(stds) > 4 else ""})</span>' if stds else "")
            + "</div>" + parent_ech(d))


def field_row(d):
    marks = ""
    if d.get("sensitive"):
        marks += f' <span class="b mk">⛨ {esc(render_label(LABELS.SENS, d["sensitive"]))}</span>'
    units = [s for s in (d.get("subfields") or []) if isinstance(s, dict)] or [d]
    if any(u.get("register") for u in units):
        marks += ' <span class="b mk">↺ Einwohnerregister</span>'
    typ = render_label(LABELS.DFTYPE, d.get("data_type"))
    subs = [s.get("name") if isinstance(s, dict) else s for s in (d.get("subfields") or [])]
    subs_txt = (f'<div class="small muted">Teilfelder: {esc(cut(" · ".join(x for x in subs if x), 160))}</div>'
                if subs else "")
    typ_html = f' <span class="small muted">· {esc(typ)}</span>' if typ else ""
    pflicht = "Pflicht" if d.get("required") else '<span class="muted">optional</span>'
    return (f'<tr><td><b>{esc(d.get("name"))}</b>{typ_html}{marks}{subs_txt}</td>'
            f'<td>{pflicht}</td><td>{ech_cell(d)}</td><td>{basis_label(d)}</td></tr>')


def cat_rank(cat):
    """Place of a category inside its tier (DATA.labels.cat_order)."""
    order = {c: i for i, c in enumerate(LAB.get("cat_order") or [])}
    return order.get(cat, 99)


def todo_sorted(items):
    """Handlungsbedarf in priority order: tier (DATA.labels.stufen — the data
    standard first), then DATA.labels.cat_order, then the larger item."""
    return sorted(items, key=lambda it: (item_stufe(it), cat_rank(it.get("cat")), -(it.get("n") or 0)))


def todo_label(cat):
    """Reader's name of a Handlungsbedarf category (plain text — the caller escapes)."""
    c = TODO.get(cat)
    return c[1] if c else f"⟨{cat}⟩"


def todo_html(f):
    """form.handlungsbedarf as computed ONCE in export_json.py, worded by
    DATA.labels.todo_cats, grouped by priority tier; the tone says who acts."""
    items = form_items(f)
    if not items:
        return st("ok", "keine offenen Punkte")
    out, cur = [], None
    for it in todo_sorted(items):
        if item_stufe(it) != cur:
            cur = item_stufe(it)
            name, expl = stufe_of(cur)
            out.append(f"<div class='tier' title='{esc(expl)}'>{esc(name)}</div>")
        t = item_ton(it)
        n = it.get("n") or 0
        det = cut(it.get("detail") or "", 240)
        tail = " — ".join(x for x in (esc(ton_label(t)), esc(det)) if x)
        out.append(f"<div class='todo'>{st(t, esc(todo_label(it.get('cat'))) + esc(count_txt(it.get('cat'), n)))}"
                   + (f" <span class='small muted'>{tail}</span>" if tail else "") + "</div>")
    return "".join(out)


def prio_html(forms):
    """The service's Handlungsbedarf at a glance: form.handlungsbedarf summed per
    category over its Formulare (plus the data-standard gaps it has no category
    for), one row per priority tier, data standard first."""
    agg = {}
    for f in forms:
        for it in form_items(f):
            a = agg.setdefault((it.get("cat"), item_ton(it)), {"n": 0, "forms": set(), "stufe": item_stufe(it)})
            a["n"] += it.get("n") or 0
            a["forms"].add(f.get("id"))
    tiers = [x[0] for x in (LAB.get("stufen") or [])]
    tiers += sorted({a["stufe"] for a in agg.values()} - set(tiers))
    rows = []
    for nr in tiers:
        name, expl = stufe_of(nr)
        cell = []
        for (cat, t), a in sorted(agg.items(), key=lambda kv: (cat_rank(kv[0][0]), -kv[1]["n"])):
            if a["stufe"] != nr:
                continue
            cell.append(st(t, esc(todo_label(cat)) + esc(count_txt(cat, a["n"])))
                        + (f" <span class='small muted nw'>in {esc(len(a['forms']))} von {esc(len(forms))} Formularen</span>"
                           if len(forms) > 1 else ""))
        rows.append(f"<tr><th title='{esc(expl)}'>{esc(name)}</th><td>"
                    + (" · ".join(cell) if cell else "<span class='small muted'>keine offenen Punkte</span>")
                    + "</td></tr>")
    return ("<h2>Handlungsbedarf nach Priorität</h2>"
            "<div class='small muted'>Lücken, die noch zu schliessen sind — der Datenstandard zuerst. Die Zahl sagt, "
            "wie viele Datenpunkte, Felder oder Formularpaare betroffen sind; ein Punkt ohne Zahl betrifft das Formular "
            "als Ganzes. Einzelheiten je Formular unten.</div>"
            f"<table class='prio'><tbody>{''.join(rows)}</tbody></table>" + ton_key_html())


def ergebnis_html(out, forms, s=None):
    ea = out.get("entscheid_art")
    if not forms:
        # the Verfahren is modelled on a Formular; no Formular, no Verfahren — said
        # without «nicht modelliert», which the head line uses for the DVSH state
        val = ('<span class="small muted">in der Databank nicht erfasst — das Verfahren wird am Formular '
               'modelliert, und für diesen Service liegt keines in der Databank</span>')
    elif not ea:
        # no point of form.handlungsbedarf stands behind this line (the priority table, the
        # Recherche page and the dashboard count none), so it carries no status badge:
        # without a DVSH model there is no Ablauftext to derive it from; with one, it is
        # simply not derived yet
        if (s or {}).get("dvsh") is None:
            val = ('<span class="small muted">nicht erfasst — der Service ist im DVSH nicht modelliert, es liegt '
                   'kein Ablauftext vor, aus dem es sich ableiten liesse</span>')
        else:
            val = '<span class="small muted">noch nicht aus dem DVSH-Ablauftext abgeleitet</span>'
    elif ea == "unbekannt":
        val = st(cat_ton("entscheid_art"), esc(render_label(LABELS.OUTCOME, ea)))
    else:
        val = (esc(render_label(LABELS.OUTCOME, ea))
               + (f' — «{esc(out["ergebnis_dokument"])}»' if out.get("ergebnis_dokument") else "")
               + ' <span class="small muted">(aus dem DVSH-Ablauftext abgeleitet)</span>')
    return f"<div><b>Ergebnis des Verfahrens:</b> {val}</div>"


def rechtsmittel_html(out):
    """The remedy line in its four states: stated (sektoral / VRG confirmed / VRG
    default), assessed and open, not yet assessed, outcome itself not backed."""
    rm = out.get("rechtsmittel")
    stt = out.get("rechtsmittel_status")
    if rm:
        frist = f"innert {esc(rm['frist_tage'])} Tagen" if rm.get("frist_tage") else "Frist im Gesetz nicht beziffert"
        nr = ((("SR " if rm.get("jurisdiction_level") == "federal" else "SHR ") + str(rm["sr_number"])) if rm.get("sr_number")
              else (rm.get("cantonal_ref") or ""))
        what = (f"Rechtsmittel nach {esc(rm.get('instanz') or 'dem verwiesenen Erlass')}" if rm.get("rechtsmittel_art") == "verweis"
                else f"<b>{esc(render_label(LABELS.RM, rm.get('rechtsmittel_art')))}</b>"
                     f"{(' an ' + esc(rm['instanz'])) if rm.get('instanz') else ''} {frist}")
        if rm.get("scope") == "allgemein":
            if stt == "default_allgemein":
                src = (st(ton_of("rechtsmittel", stt), esc(render_label(LABELS.RM_STATUS, stt))) + ' '
                       '<span class="small muted">VRG Art. 1: die allgemeine Regel gilt nur, soweit kein Fachgesetz abweicht — '
                       'ob eines vorgeht, hat noch kein Prüfvermerk bestätigt.</span>')
            else:
                src = st(ton_of("rechtsmittel", "bestaetigt"),
                         "allgemeine Regel des VRG — Prüfvermerk bestätigt, kein vorgehendes Fachgesetz")
        else:
            src = st(ton_of("rechtsmittel", "bestaetigt"), f'sektoral: {esc(rm.get("short_title") or rm.get("law_title") or "")}')
        h = [f'<div><b>Rechtsmittel:</b> {what} — {esc(rm.get("article_no"))} {esc(rm.get("short_title") or rm.get("law_title") or "")}'
             f'{(" (" + esc(nr) + ")") if nr else ""} {src}</div>',
             f'<div class="small muted">«{esc(cut(rm.get("quote"), 300))}»</div>']
        if rm.get("frist_quote"):
            h.append(f'<div class="small muted">«{esc(cut(rm["frist_quote"], 300))}»</div>')
        if rm.get("hinweis"):
            h.append(f'<div class="small muted">{esc(rm["hinweis"])}</div>')
        h.append(verdikt_html(out))
        return "".join(h)
    if out.get("entscheid_art") == "kein_entscheid":
        return '<div><b>Rechtsmittel:</b> <span class="muted">keines — das Verfahren endet ohne anfechtbare Verfügung (Meldung)</span></div>'
    if not stt:
        return ""
    h = [f'<div><b>Rechtsmittel:</b> {st(ton_of("rechtsmittel", stt), esc(render_label(LABELS.RM_STATUS, stt)))}']
    if stt in ("beurteilt_offen", "nicht_beurteilt"):
        lv = " und ".join(EBENE.get(x) or render_label(LABELS.JUR, x) for x in (out.get("gesetzesebenen") or [])) \
             or "die zitierten Erlasse"
        h.append(f' <span class="small muted">Der Entscheid stützt sich auf {esc(lv)}'
                 f'{"; Registerverfahren haben oft eine eigene Rechtsmittelordnung" if out.get("entscheid_art") == "registereintrag" else ""}.'
                 f'{" Eine Lücke der Databank, kein Befund über die Verwaltung." if stt == "nicht_beurteilt" else ""}</span>')
    elif stt == "entscheidart_offen":
        h.append(' <span class="small muted">Erst wenn feststeht, was das Verfahren zurückgibt, lässt sich die '
                 'zuständige Rechtsmittelnorm bestimmen.</span>')
    h.append("</div>")
    h.append(verdikt_html(out))
    return "".join(h)


def rm_quelle_label(code):
    """rechtsmittel_quelle ∈ {allgemein, sektoral, offen}: the first two are the scope
    vocabulary (labels.SCOPE); «offen» is what export_json turns into the status
    beurteilt_offen (labels.RM_STATUS) — no third label source, unknown codes ⟨…⟩."""
    if code == "offen":
        return render_label(LABELS.RM_STATUS, "beurteilt_offen")
    return render_label(LABELS.SCOPE, code)


def verdikt_html(out):
    """The panel's note, stored as «quelle: begruendung»."""
    v = out.get("rechtsmittel_verdikt")
    if not v:
        return ""
    m = re.match(r"^(\w+):\s*(.+)$", v, re.S)
    return (f'<div class="small muted">Prüfvermerk ({esc(rm_quelle_label(m.group(1)))}): {esc(m.group(2))}</div>' if m
            else f'<div class="small muted">Prüfvermerk: {esc(v)}</div>')


def formless_html(s, dv):
    """What a service without a Formular in the databank really is, per the DVSH."""
    if s.get("dvsh") is None:
        # in_dvsh=1 without a row: the service IS in the DVSH, only its
        # modelling is missing from the current harvest — not «nicht modelliert»
        head = ("DVSH-Modellierung nicht in der Databank" if s.get("in_dvsh") else "Nicht im DVSH modelliert")
        return (f"<div class='box small'>{esc(head)}; kein Formular in der Databank — "
                "weder eine Feld-Schicht noch ein Verfahren ist erfasst.</div>")
    ep = dv.get("endpoint_typ")
    txt = f"Kein Formular in der Databank — laut DVSH Kanal: {esc(render_label(LABELS.ENDPOINT, ep) or 'im DVSH nicht angegeben')}"
    if ep == "eformular":
        fd = dv.get("form_definitions")
        if isinstance(fd, str):
            try: fd = json.loads(fd)
            except Exception: fd = []
        nfel = sum(len(x.get("felder") or []) for x in (fd or []) if isinstance(x, dict))
        txt += (f" — im DVSH sind {esc(pl(nfel, 'Feld', 'Felder'))} hinterlegt, die Feld-Schicht ist in der Databank noch nicht erhoben"
                if nfel else " — im DVSH sind keine Felder hinterlegt, in der Databank gibt es keine Feld-Schicht")
    return f"<div class='box small'>{txt}.</div>"


def legend_html():
    tiers = " · ".join(esc(stufe_of(x[0])[0]) for x in (LAB.get("stufen") or []))
    return ("<div class='legend'><b>Legende</b>" + ton_key_html()
            + "<div><b>Kennzeichen, keine Bewertung</b> (weiss, umrandet): ⛨ = besonders schützenswerte Personendaten · "
            "↺ = das Einwohnerregister führt diese Angabe bereits (Once-Only, nur Daten natürlicher Personen; gezählt je Teilfeld) · "
            "Bund / Kanton / interkantonal = Rechtsebene des Erlasses; Ebene offen = die Ebene lässt sich aus dem "
            "DVSH-Eintrag nicht belegen (kein amtlicher Link, keine SR-/SHR-Nummer, kein bekannter Kurztitel).</div>"
            "<div><b>Violett, gestrichelt:</b> eSH = Entwurf eines kantonalen Standards, kein offizieller eCH-Standard.</div>"
            f"<div><b>Handlungsbedarf nach Priorität:</b> {tiers} — innerhalb einer Stufe in fester Reihenfolge.</div>"
            "<div><b>Weitere Zeichen:</b> "
            "⟨Typ⟩ = Datentyp gemäss eCH-XSD · Element offen = Standard zugeordnet, XML-Element noch nicht bestimmt · "
            f"Teilfelder — {esc(TON_SYM['ok'])} … {esc(TON_SYM['dec'])} … = Stand der einzelnen Teilfelder eines zusammengesetzten Feldes (die Teilfelder sind die "
            "Einheit des Datenstandards); «Feld als Ganzes» nennt nur, was dem übergeordneten Feld zugeordnet ist, ohne Bewertung · "
            "Standard ohne Elementkatalog = in der Databank ist für diesen Standard kein XML-Elementkatalog hinterlegt "
            "(Prozess-/FHIR-Standard oder XSD nicht eingelesen); die Zuordnung bleibt auf Standard-Ebene · "
            f"{esc(render_label(LABELS.DIV, 'pflicht_uneinheitlich'))} = die Formulare sind sich uneins, eine kantonale Festlegung fehlt · "
            "Min. = Rechenmodell 0.4 Min. je Pflichtangabe + 5 Min. je Beilage, keine Messung; Beilage = jeder Eintrag der "
            f"Beilagenliste (Formular und DVSH) plus Felder vom Datentyp {esc(render_label(LABELS.DFTYPE, 'attachment'))} ohne "
            "Listeneintrag, ohne Gewichtung nach Pflicht.</div></div>")


def foot_html():
    ds, oc, xs = DATENSTAND, (DATENSTAND.get("online_check") or {}), (DATENSTAND.get("xsd_sweep") or {})
    bits = [f"Export {fmt_date(STAND)}"]
    if ds.get("dvsh_stand"):
        bits.append(f"DVSH-Stand {fmt_date(ds['dvsh_stand'])}")
    if ds.get("shep_harvest"):
        bits.append(f"SHEP-Abzug {fmt_date(ds['shep_harvest'])}")
    if oc.get("date"):
        # the last FULL pass and the recheck since — the same two dates the
        # dashboard's Datenstand line names (a recheck of 98 Formulare is not
        # «zuletzt geprüft» for all 474)
        full = oc.get("full_date") or oc["date"]
        recheck = (f", Nachprüfung {fmt_date(oc['date'])} ({pl(oc.get('n_recent') or 0, 'Formular', 'Formulare')})"
                   if oc.get("full_date") and oc["date"] != oc["full_date"] else "")
        bits.append(f"Online-Prüfung vollständig {fmt_date(full)}{recheck} — {oc.get('n_checked', 0)} von {oc.get('n_forms', 0)} "
                    f"Formularen geprüft, {pl(oc.get('n_overdue', 0), 'Wiedervorlage überfällig', 'Wiedervorlagen überfällig')}, "
                    f"{oc.get('n_never', 0)} nie geprüft")
    if xs.get("date"):
        bits.append(f"eCH-XSD-Abgleich {fmt_date(xs['date'])} ({pl(xs.get('n') or 0, 'Standard', 'Standards')})")
    z = ZITATE or {}
    zit = (f" Zitate der Rechtsgrundlagen: {nf(z.get('verifiziert'))} verifiziert (Bundesrecht, aus dem amtlichen "
           f"Fedlex-Text gelesen) · {nf(z.get('quelle_pdf'))} aus dem amtlichen Gesetzes-PDF gelesen (kantonales Recht: "
           f"Schaffhauser Rechtsbuch) · {nf(z.get('unverifiziert'))} unverifiziert." if z else "")
    return ("<div class='foot'>Quelle: citygov.db (Feld-Schicht kuratiert; Rechtsgrundlagen gegen die amtlichen Gesetzestexte geprüft; "
            "eCH aus den offiziellen XSDs; Empfänger und Fristen nur mit Artikel-Beleg). Offene Punkte sind Lücken — noch zu "
            "klären oder noch nicht belegt; grau markierte sind Hausaufgaben der Databank, kein Befund über die Verwaltung. "
            + st(ton_of("schutzstufe", "fehlt"), "Schutzstufen (ISV) nicht festgelegt")
            + f" — für die Felder steht der kantonale Entscheid noch aus.<br>Datenstand: {esc(' · '.join(bits))}.{esc(zit)}</div>")


def dossier(s, forms, kontakt):
    """One dossier page. kontakt = the contact parts of the service's Dienststelle
    (dienststellen_uebersicht[].kontakt, the list the dashboard draws)."""
    dv = s.get("dvsh") or {}
    kontakt = list(kontakt or [])
    # the DVSH contact starts with the office name, which the line above already says
    if kontakt and str(kontakt[0]).strip().lower() == (s.get("dienststelle") or "").strip().lower():
        kontakt = kontakt[1:]
    laws = []
    for key in ("recht_kantonal", "recht_bund"):
        v = dv.get(key)
        if isinstance(v, str):
            try: v = json.loads(v)
            except Exception: v = []
        items = [x for x in (v or []) if isinstance(x, dict)]
        # abbreviation -> level, from the entries of THIS list whose level is
        # established; a bare "Art. 3 GesG" then inherits it
        local = {}
        if key == "recht_bund":
            for x in items:
                lb = (x.get("titel") or x.get("label") or "").strip()
                j = jur_of_ref(x, lb)
                if j == "Ebene offen":
                    continue
                for a in abbrs_of(lb):
                    local[a.lower()] = j
        for x in items:
            label = (x.get("titel") or x.get("label") or "").strip()
            if not label:
                continue
            # the DVSH's second list is free text and often cantonal law; the
            # level is read from evidence, never from the list's name
            jl = "Kanton" if key == "recht_kantonal" else jur_of_ref(x, label, local)
            nr = x.get("ssr_nummer") or x.get("sr_nummer") or ""
            chip = f'{esc(jl)} · {esc(label)}{(" · " + esc(nr)) if nr else ""}'
            url = web_href(x.get("url"))
            if url:
                laws.append(f'<a class="b mk" href="{url}" target="_blank" rel="noreferrer">{chip}</a>')
            else:
                laws.append(f'<span class="b mk">{chip}</span>')
    # the Entscheid is modelled on ONE of a service's Formulare; picking the
    # first blindly hid the proven Rechtsmittel of the others
    out = next((f["outcome"] for f in forms
                if f.get("outcome") and (f["outcome"].get("rechtsmittel") or f["outcome"].get("entscheid_art"))),
               (forms[0].get("outcome") if forms else None)) or {}
    rm_html = rechtsmittel_html(out)
    if s.get("dvsh") is None:
        # the dashboard's two states (build_dashboard.py, nodvbox): linked in the
        # DVSH but the row is absent from the harvest, vs. not modelled at all
        dv_txt = ("DVSH-Modellierung nicht in der Databank (im DVSH verknüpft, beim letzten Abzug nicht mitgeliefert)"
                  if s.get("in_dvsh") else "nicht modelliert")
    else:
        dv_txt = render_label(LABELS.DVSH_STATUS, dv.get("status")) or "Statuswert im DVSH nicht angegeben"
    if s.get("dvsh_n"):
        dv_txt += f" · eine von {s['dvsh_n']} DVSH-Modellierungen"          # escaped with dv_txt below
    h = [GENERATED,
         f"<!DOCTYPE html><html lang='de'><head><meta charset='utf-8'>{HEAD}<title>Datenschutz-Dossier · {esc(s['name'])}</title><style>{CSS}</style></head><body>",
         "<button class='print' onclick='window.print()'>⎙ Drucken / als PDF sichern</button>",
         f"<div class='nav'><a href='index.html'>← Alle Dossiers</a> "
         f"<a href='{page_href('../dashboard.html', 'fields/' + str(s['id']))}'>Service in der Databank</a></div>",
         f"<div class='sub'>Kanton Schaffhausen · Compliance-Databank · Datenschutz-Dossier · Stand {esc(fmt_date(STAND))}</div>",
         f"<h1>{esc(s['name'])}</h1>",
         f"<div class='sub'>{' · '.join(esc(x) for x in (s.get('dienststelle'), s.get('department')) if x)}</div>",
         # the contact of the Dienststelle, worded as in the dashboard; telephone and e-mail are links
         f"<div class='sub'>{kontakt_html(kontakt)}</div>",
         "<div class='grid'>",
         f"<div><b>DVSH-Status:</b> {esc(dv_txt)}{' · online' if dv.get('online') else ''}"
         f"{(' · Vollzug: ' + esc(dv.get('vollzugsbehoerde'))) if dv.get('vollzugsbehoerde') else ''}</div>",
         ergebnis_html(out, forms, s),
         "</div>"]
    if dv.get("kurzbeschreibung"):
        h.append(f"<div class='small'>{esc(cut(dv['kurzbeschreibung'], 400))}</div>")
    if s.get("themen"):
        h.append("<div class='small gap4'><b>Themengruppe (eCH-0049):</b> " + " · ".join(
            f"{esc(t.get('gruppe'))} <span class='muted'>({esc(render_label(LABELS.KAT, t.get('katalog')))}, {esc(t.get('bereich'))})</span>"
            for t in s["themen"]) + "</div>")
    if forms:
        h.append(prio_html(forms))
    if laws:
        h.append("<h2>Rechtsgrundlagen des Services (DVSH)</h2><div>" + " ".join(laws) + "</div>")
    if rm_html:
        h.append("<h2>Rechtsmittel gegen den Entscheid</h2>" + rm_html)
    for f in forms:
        dfs = f.get("data_fields") or []
        bu = f.get("burden") or {}
        h.append(f"<div class='form'><h2>Formular: {esc(f['title'])}</h2>")
        facts = [esc(render_label(LABELS.CHAN, f.get("submission_channel")) or LABELS.CHAN["unbekannt"])]   # every fact is ready HTML
        if f.get("signature_requirement"):
            facts.append("Unterschrift: " + esc(render_label(LABELS.SIG, f["signature_requirement"])))
        if bu:
            # the model figure as the dashboard prints it (JS number: 7.0 -> «7», 61.2 -> «61.2»)
            mins = bu.get("minutes") or 0
            mins = int(mins) if float(mins).is_integer() else mins
            facts.append(esc(f"Bürgerlast: {pl(bu.get('inputs', 0), 'Pflichtangabe', 'Pflichtangaben')} (Teilfelder) · "
                             f"{pl(bu.get('attachments', 0), 'Beilage', 'Beilagen')} · ~{mins} Min. (Modell) · "
                             f"{bu.get('prefillable', 0)} aus dem Einwohnerregister vorbefüllbar"))
        if f.get("purpose"):
            facts.append("Zweck: " + esc(f["purpose"]))
        ck = f.get("check") or {}
        # the Wiedervorlage is export_json's item «pruefung_faellig»: past it (or
        # never checked) the currency is open again — the Databank checks
        faellig = any(it.get("cat") == "pruefung_faellig" for it in f.get("handlungsbedarf") or [])
        if ck.get("status") and ck["status"] != "aktuell":
            facts.append(st(ton_of("check", ck["status"]), esc(render_label(LABELS.CHECK, ck["status"]))))
        elif ck.get("d"):
            facts.append(st(ton_of("check", "faellig" if faellig else "aktuell"),
                            f'Online-Fassung geprüft {esc(fmt_date(ck["d"]))}' + (" · Wiedervorlage fällig" if faellig else "")))
        elif not ck and faellig:
            facts.append(st(ton_of("check", "nie"), "Online-Fassung noch nie geprüft"))
        h.append("<div class='small'>" + " · ".join(facts) + "</div>")
        if dfs:
            h.append("<h3>Verlangte Daten</h3><table><thead><tr><th>Datenfeld</th><th>Pflicht</th><th>Standard / Datentyp</th><th>Rechtsgrundlage</th></tr></thead><tbody>")
            h.extend(field_row(d) for d in dfs)
            h.append("</tbody></table>")
        sd = f.get("standard_divergenzen") or {}
        ang, feh = sd.get("angleichen") or [], sd.get("fehlend") or []
        bz = sd.get("bezeichnungen") or []
        if ang or feh or bz:
            nang = sd.get("n_angleichen", sum(1 for i in ang if i["art"] != "pflicht_uneinheitlich"))
            nunk = sd.get("n_pflicht_ungeklaert", sum(1 for i in ang if i["art"] == "pflicht_uneinheitlich"))
            nfeh = sd.get("n_fehlend", 0)
            parts = []
            if nang: parts.append(f"{nang} anzugleichen")
            if nunk: parts.append(f"{nunk} {render_label(LABELS.DIV, 'pflicht_uneinheitlich')}")
            if feh and nfeh: parts.append(pl(nfeh, "Punkt", "Punkte") + " ohne Standard")
            h.append(f"<h3>Standard-Divergenzen{esc(' (' + ' · '.join(parts) + ')') if parts else ''}</h3>"
                     + "<div class='small muted'>Was dieses Formular davon trennt, Teil eines einheitlichen "
                       "Datenstandards zu sein: oben dieselbe Angabe anders verlangt als anderswo, unten Daten "
                       "ohne zitierbaren Standard.</div>")
            if ang:
                h.append("<table><thead><tr><th>Datenfeld</th><th>Art</th><th>hier</th>"
                         "<th>auf den übrigen Formularen</th><th>Rechtsgrundlage hier</th></tr></thead><tbody>")
                for i in ang:
                    h.append(f"<tr><td><b>{esc(i['feld'])}</b>"
                             + (f" › {esc(i['teilfeld'])}" if i.get("teilfeld") else "")
                             + f"<div class='mono'>{esc(i.get('standard'))} {code_name(i.get('element'))}</div></td>"
                             f"<td class='small'>{esc(render_label(LABELS.DIV, i['art']))}</td>"
                             f"<td class='small'>{st(ton_of('div', i['art']), esc(i['hier']))}</td>"
                             f"<td class='small'>{esc(i['andere'])}</td>"
                             f"<td class='small'>{esc(i.get('basis') or '')}</td></tr>"
                             f"<tr><td colspan='5' class='small muted'>→ {esc(i['aktion'])}</td></tr>")
                h.append("</tbody></table>")
            var = [i for i in bz if i["klasse"] == "variante"]
            auf = [i for i in bz if i["klasse"] == "pruefen" and i.get("pruefart") == "aufteilen"]
            zuo = [i for i in bz if i["klasse"] == "pruefen" and i.get("pruefart") != "aufteilen"]
            if var:
                h.append("<div class='small gap6'>" + st(ton_of("begriff", "variante"), "Umbenennen")
                         + " — gleiche Angabe, anderer Name: "
                         + " · ".join(f"«{esc(i.get('hier'))}» → <b>«{esc(i.get('vorschlag'))}»</b>" for i in var) + "</div>")
            if auf:
                h.append("<div class='small gap6'>"
                         + st(ton_of("begriff", "aufteilen"), "Feld bündelt mehrere Daten — aufteilen") + " "
                         + " · ".join(f"«{esc(i.get('hier'))}»" for i in auf) + "</div>")
            if zuo:
                h.append("<div class='small muted gap6'>" + st(ton_of("begriff", "zuordnung"), esc(todo_label("zuordnung")))
                         + " (Aufgabe der Databank, nicht des Formulars): "
                         + " · ".join(f"«{esc(i.get('hier'))}» ≠ {esc(i.get('standard'))} {esc(i.get('element'))}" for i in zuo) + "</div>")
            if feh:
                h.append("<div class='small'>" + " ".join(
                    f"<div class='gap2'>{st(ton_of('div', i['art']), esc(render_label(LABELS.DIV, i['art'])))}"
                    + (f" ({esc(i['standard'])})" if i.get("standard") else "")
                    + f": {esc(pl(i['n'], 'Datenpunkt', 'Datenpunkte'))} — {esc(' · '.join(i['felder']))}"
                    + ("…" if i["n"] > len(i["felder"]) else "")
                    + f"<div class='muted'>→ {esc(i['aktion'])}</div></div>"
                    for i in feh) + "</div>")
        if f.get("beilagen"):
            parts = []
            for b in f["beilagen"]:
                hl = render_label(LABELS.HALTER, b.get("halter"))
                if b.get("fetchable"):
                    parts.append(f"{esc(b['bezeichnung'])} <span class='b mk'>Once-Only möglich · Halter: {esc(hl)}</span>")
                else:
                    parts.append(f"{esc(b['bezeichnung'])}" + (f" <span class='muted'>(Halter: {esc(hl)})</span>" if hl else ""))
            h.append("<h3>Beilagen</h3><div class='small'>" + " · ".join(parts) + "</div>")
        if f.get("disclosures"):
            h.append("<h3>Empfänger (belegte Bekanntgaben)</h3><div class='small'>" + " · ".join(
                f"{esc(x['empfaenger'])} <span class='muted'>({esc(render_label(LABELS.MODE, x.get('mode')))}"
                f"{(', ' + esc(x.get('short_title') or '') + ' ' + esc(x.get('article_no') or '')) if x.get('article_no') else ''})</span>"
                for x in f["disclosures"]) + "</div>")
        else:
            h.append("<h3>Empfänger</h3><div class='small'>" + st(cat_ton("empf"), "keine belegte Bekanntgabe erfasst")
                     + " <span class='muted'>— offen, bis eine Bekanntgabe mit Artikel belegt oder ihr Fehlen festgehalten ist</span></div>")
        ret = f.get("retention") or []
        if ret:
            h.append("<h3>Aufbewahrung / Löschung</h3><div class='small'>" + " ".join(
                f"<div>• {esc(r.get('summary') or '')} <span class='muted'>({esc(r.get('short_title') or '')} {esc(r.get('article_no') or '')})</span></div>"
                for r in ret[:4]) + "</div>")
        else:
            # the ONE default sentence, computed in export_json.py for every surface
            t = TEXTE.get("aufbewahrung_standard") or {}
            refs = " · ".join(f"SHR {r[0]} {r[1]}" for r in (t.get("refs") or []) if isinstance(r, (list, tuple)) and len(r) >= 2)
            h.append("<h3>Aufbewahrung / Löschung</h3><div class='small muted'>"
                     + (esc(t["text"]) + (f" <span class='mono'>Belege: {esc(refs)}</span>" if refs else "") if t.get("text")
                        else "keine sektorale Frist erfasst — die Standardregel ist im Export nicht hinterlegt (offen)")
                     + "</div>")
        h.append("<h3>Handlungsbedarf</h3><div class='small'>" + todo_html(f) + "</div></div>")
    if not forms:
        h.append(formless_html(s, dv))
    h.append(legend_html())
    h.append(foot_html() + "</body></html>")
    return "\n".join(x for x in h if x)


def main():
    global STAND, TEXTE, DATENSTAND, ZITATE, LAB, TODO
    pdf = "--pdf" in sys.argv
    only = None
    if "--only" in sys.argv:
        only = int(sys.argv[sys.argv.index("--only") + 1])
    with open(os.path.join(ROOT, "data_export.json"), encoding="utf-8") as fh:
        D = json.loads(gap_wording(fh.read()))
    STAND = (D.get("generated_at") or "")[:10]
    TEXTE = D.get("texte") or {}
    DATENSTAND = D.get("datenstand") or {}
    ZITATE = D.get("zitate") or {}
    # the dashboard's DATA.labels; labels.py only fills a key an older export lacks
    LAB = {**LABELS.as_export(), **(D.get("labels") or {})}
    TODO = {c[0]: c for c in (LAB.get("todo_cats") or [])}
    for l in D.get("laws", []):
        s = (l.get("short_title") or "").strip()
        if 2 <= len(s) <= 24 and ";" not in s:
            LAWJUR[s.lower()] = l.get("jurisdiction_level")
    # the contact parts per Dienststelle — the list the dashboard draws
    kontakt_of = {d["name"]: d.get("kontakt") or [] for d in D.get("dienststellen_uebersicht", [])}
    by_svc = {}
    for f in D["forms"]:
        by_svc.setdefault(f["service_id"], []).append(f)
    # the dossier words the states the export stamped; an export from before that
    # step would print every data point as «nicht geprüft» — stop instead
    alt = next((f["id"] for f in D["forms"] for d in f.get("data_fields") or []
                if "ech_state" not in d or "basis_state" not in d), None)
    if alt is not None:
        sys.exit(f"ABBRUCH export_dossiers.py — nichts geschrieben: data_export.json ist älter als export_json.py "
                 f"(Formular {alt}: Datenfeld ohne ech_state/basis_state). Zuerst python3 scripts/export_json.py ausführen.")
    os.makedirs(OUT, exist_ok=True)
    index = []
    n = 0
    for s in sorted(D["services"], key=lambda x: (x.get("department") or "", x["name"])):
        if only and s["id"] != only:
            continue
        # the file name: ONE rule (common.dossier_slug), exported as services[].dossier_slug
        # — the name the dashboard links to
        slug = s.get("dossier_slug") or ""
        if not re.fullmatch(r"[a-z0-9-]+", slug):      # a file name is never taken unchecked
            slug = dossier_slug(s)
        page = dossier(s, by_svc.get(s["id"], []), kontakt_of.get(s.get("dienststelle")))
        open(os.path.join(OUT, slug + ".html"), "w", encoding="utf-8").write(page)
        index.append((s, slug, len(by_svc.get(s["id"], []))))
        n += 1
        if pdf and os.path.exists(CHROME):
            subprocess.run([CHROME, "--headless=new", "--disable-gpu", "--no-pdf-header-footer",
                            f"--print-to-pdf={os.path.join(OUT, slug + '.pdf')}",
                            "file://" + os.path.join(OUT, slug + ".html")],
                           capture_output=True, timeout=120)
    if not only:
        # the PDF column only in a --pdf run and only when at least one PDF exists
        # (an always-empty column reads as a rendering error). A plain build never
        # links a PDF: they are local files, and a committed index must not point
        # at PDFs the published site does not carry
        pdf_any = pdf and any(os.path.exists(os.path.join(OUT, slug + ".pdf")) for _, slug, _ in index)
        tier1 = first_tier()      # the data standard leads

        def who_cell(sid, first):
            """The service's open points (form.handlungsbedarf plus the data-standard
            gaps it has no category for, as in the dossier's priority block) summed
            by tone, the data-standard tier or the others — red, amber, grey; green
            is no open point."""
            c = {"act": 0, "dec": 0, "open": 0}
            for f in by_svc.get(sid, []):
                for it in form_items(f):
                    if (item_stufe(it) == tier1) == first and item_ton(it) in c:
                        c[item_ton(it)] += it.get("n") or 0
            # tone + symbol + number; the word (who acts) is in the chip for a screen
            # reader and in the legend above the table for the eye
            chips = [st(t, f"<span class='vh'>{esc(ton_short(t))}: </span>{esc(nf(c[t]))}", short=True)
                     for t in ("act", "dec", "open") if c[t]]
            return " ".join(chips) if chips else "<span class='muted'>–</span>"

        def pdf_cell(slug):
            return (f"<a href='{page_href(slug + '.pdf')}'>PDF</a>"
                    if os.path.exists(os.path.join(OUT, slug + ".pdf")) else "")
        rows = "".join(f"<tr><td>{esc(s.get('department') or '')}</td><td><a href='{page_href(slug + '.html')}'>{esc(s['name'])}</a></td>"
                       f"<td>{esc(s.get('dienststelle') or '')}</td><td>{esc(nforms)}</td>"
                       f"<td class='nw'>{who_cell(s['id'], True)}</td><td class='nw'>{who_cell(s['id'], False)}</td>"
                       + (f"<td>{pdf_cell(slug)}</td>" if pdf_any else "")
                       + "</tr>"
                       for s, slug, nforms in index)
        filt = ("<input class='filter' type='search' aria-label='Dossiers filtern' placeholder='Filter: Departement, Service oder Dienststelle …' "
                "oninput=\"for(const r of document.querySelectorAll('tbody tr'))r.hidden=!r.textContent.toLowerCase().includes(this.value.toLowerCase())\">")
        # marker a locally opened dashboard.html probes for: present = the whole
        # repository sits next to it (dossier/Formular/flow links work offline);
        # missing = a single saved copy, whose repository links then open online
        open(os.path.join(OUT, "_repo.js"), "w", encoding="utf-8").write(
            "/* GENERATED by scripts/export_dossiers.py - marker: the repository is present */\nwindow.__cgRepo=true;\n")
        open(os.path.join(OUT, "index.html"), "w", encoding="utf-8").write(
            GENERATED + "\n"
            f"<!DOCTYPE html><html lang='de'><head><meta charset='utf-8'>{HEAD}<title>Datenschutz-Dossiers</title><style>{CSS}</style></head><body class='idx'>"
            f"<h1>Datenschutz-Dossiers je Service</h1>"
            f"<div class='sub'><a href='../dashboard.html'>Dashboard</a> · {esc(n)} Services · Stand {esc(fmt_date(STAND))} · ein bis wenige A4-Seiten je Service, druckbar</div>"
            "<div class='small gap6'>Jedes Dossier zeigt für einen Service zuerst den Handlungsbedarf nach Priorität "
            "(der Datenstandard vorn), dann Dienststelle und Kontakt, DVSH-Status, Rechtsgrundlagen, Ergebnis des Verfahrens "
            "und Rechtsmittel, je Formular die verlangten Daten mit Pflicht, eCH-Element, Rechtsgrundlage und Kennzeichen (⛨, ↺), "
            "Standard-Divergenzen, Beilagen mit Halter, Empfänger, Aufbewahrung und den Handlungsbedarf. Alle Seiten werden aus "
            "citygov.db (über data_export.json) erzeugt. Offene Punkte sind Lücken — noch zu klären oder noch nicht belegt.</div>"
            + ton_key_html() + filt +
            "<table><thead><tr><th>Departement</th><th>Service</th><th>Dienststelle</th><th>Formulare</th>"
            "<th title='Offene Punkte der Stufe Datenstandard, nach wer als Nächstes handelt — gezählt in Datenpunkten bzw. Feldern, einschliesslich der Datenpunkte ohne eCH-Standard'>Datenstandard</th>"
            "<th title='Offene Punkte der übrigen Stufen (Rechtsgrundlage, Verfahren &amp; Verzeichnis, Bestand &amp; Aktualität), nach wer als Nächstes handelt — gezählt in Feldern, Formularen bzw. Formularpaaren'>Weitere Lücken</th>"
            f"{'<th>PDF</th>' if pdf_any else ''}</tr></thead><tbody>{rows}</tbody></table>"
            f"<div class='foot'>Datenstand: Export {esc(fmt_date(STAND))}"
            f"{(' · DVSH-Stand ' + esc(fmt_date(DATENSTAND['dvsh_stand']))) if DATENSTAND.get('dvsh_stand') else ''}.</div></body></html>")
    print(f"dossiers: {n} HTML" + (" + PDF" if pdf else "") + f" in {OUT}")


if __name__ == "__main__":
    main()
